In [5]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [6]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()


print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow dog dog a ab a aB ab abc abc poll abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a abc a abc a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a abc abc ab abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a

In [7]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'statusId': 1,
 'maxMembers': 5,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [8]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [9]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

    Palabra
0       dog
1      aaaa
2    holaaa
3      siii
4      siii
..      ...
566      aa
567      ab
568       a
569      ab
570       a

[571 rows x 1 columns]
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
15     cat
16     cat
17     cat
18     cat
19     cat
20     cat
21     cat
22     ggg
23     ggg
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7    8                                     sssss 

In [10]:
df3.head(15)

id                 name         description  creatorId  statusId  \
0    1                  cat                blue          2         1   
1    2                  dog                 red          2         1   
2    3                doggf                 red         56         1   
3    4                catff                blue         56         1   
4    5                lemur                grey         56         1   
5    6                  ppo                 ppo         56         1   
6    7                  ddd                 ddd         56         1   
7    8                sssss                 sss         56         1   
8    9                  sss                 sss         56         1   
9   10                  ggg                 ggg         56         1   
10  15     modified bruuhhh  modified testinggg         56         1   
11  17                    s                   s         56         1   
12  20        proyecto pepe    que tal soy sech         56         1   
13  21     allprojects test                sape         56         1   
14  24  getallprojects test                sest         56         1   

    maxMembers                 createdAt                 updatedAt  
0            5  2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1            5  2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2            5  2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3            5  2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4            5  2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5            5  2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6            5  2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7            5  2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8            5  2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9            5  2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10           5  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11           5  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12           5  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13           5  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14           5  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [11]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(571, 1)
(24, 1)
(53, 8)


In [12]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(53, 8)


In [13]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId  statusId  maxMembers
0     dog     dog   1    cat        blue          2         1           5
1    aaaa     cat   2    dog         red          2         1           5
2  holaaa     dog   3  doggf         red         56         1           5
3    siii     cat   4  catff        blue         56         1           5
4    siii     cat   5  lemur        grey         56         1           5
5     dog   doggf   6    ppo         ppo         56         1           5
6     dog     cat   7    ddd         ddd         56         1           5
7     dog     cat   8  sssss         sss         56         1           5
8     cat     cat   9    sss         sss         56         1           5
9     wow     cat  10    ggg         ggg         56         1           5

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tfidf = TfidfVectorizer(max_features=5000)

In [16]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [17]:
print(type(vectorized_data))

<class 'scipy.sparse.csr.csr_matrix'>


In [18]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [19]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    40   41   42   43   44   45  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 46 columns]

In [20]:
vectorized_dataframe.shape

(53, 46)

In [21]:
from sklearn.decomposition import TruncatedSVD

In [22]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [23]:
reduced_data.shape

(53, 14)

In [24]:
reduced_data

array([[ 1.73465564e-06, -6.06227429e-01,  6.71473558e-01,
        -4.00489834e-01, -1.45469265e-01, -1.13444687e-03,
        -2.94147893e-16, -2.93976208e-16,  1.67822814e-16,
        -1.50340856e-17, -1.10790054e-16,  2.24272488e-17,
        -6.62404425e-17, -5.74558634e-17],
       [-8.17869279e-07,  6.79224044e-01,  3.65386179e-01,
        -1.95470757e-01, -6.05682388e-01, -8.35468546e-05,
         1.80394311e-16,  3.98894681e-17, -4.60323352e-17,
         1.12077627e-16,  1.56192787e-16, -2.00211589e-17,
        -1.16608118e-16, -1.84546370e-16],
       [-8.17869279e-07,  6.79224044e-01,  3.65386179e-01,
        -1.95470757e-01, -6.05682388e-01, -8.35468546e-05,
         1.80394311e-16,  3.98894681e-17, -4.60323352e-17,
         1.12077627e-16,  1.56192787e-16, -2.00211589e-17,
        -1.16608118e-16, -1.84546370e-16],
       [ 1.73465564e-06, -6.06227429e-01,  6.71473558e-01,
        -4.00489834e-01, -1.45469265e-01, -1.13444687e-03,
        -2.94147893e-16, -2.93976208e-16,  1.

In [25]:
svd.explained_variance_ratio_.cumsum()

array([0.08832668, 0.13702106, 0.17861188, 0.22786647, 0.27705428,
       0.31888992, 0.34126137, 0.36337416, 0.38799681, 0.41261964,
       0.43724802, 0.46138904, 0.48601715, 0.50994839])

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
similarity = cosine_similarity(reduced_data)

In [28]:
similarity

array([[ 1.00000000e+00, -2.47720008e-05, -2.47720008e-05, ...,
        -5.07826197e-04, -3.85902400e-03, -2.53432190e-04],
       [-2.47720008e-05,  1.00000000e+00,  1.00000000e+00, ...,
         4.15419296e-05,  2.42437726e-04,  6.09700669e-03],
       [-2.47720008e-05,  1.00000000e+00,  1.00000000e+00, ...,
         4.15419296e-05,  2.42437726e-04,  6.09700669e-03],
       ...,
       [-5.07826197e-04,  4.15419296e-05,  4.15419296e-05, ...,
         1.00000000e+00,  3.09608829e-01,  2.49984014e-01],
       [-3.85902400e-03,  2.42437726e-04,  2.42437726e-04, ...,
         3.09608829e-01,  1.00000000e+00,  4.37992187e-01],
       [-2.53432190e-04,  6.09700669e-03,  6.09700669e-03, ...,
         2.49984014e-01,  4.37992187e-01,  1.00000000e+00]])

In [29]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 9.99943136e-01, -2.47702107e-05, -2.47702107e-05, ...,
        -3.89699256e-04, -2.26672154e-03, -1.28159819e-04],
       [-2.47702107e-05,  9.99912342e-01,  9.99912342e-01, ...,
         3.18782486e-05,  1.42401383e-04,  3.08318861e-03],
       [-2.47702107e-05,  9.99912342e-01,  9.99912342e-01, ...,
         3.18782486e-05,  1.42401383e-04,  3.08318861e-03],
       ...,
       [-3.89699256e-04,  3.18782486e-05,  3.18782486e-05, ...,
         5.88916398e-01,  1.39563934e-01,  9.70155876e-02],
       [-2.26672154e-03,  1.42401383e-04,  1.42401383e-04, ...,
         1.39563934e-01,  3.45037328e-01,  1.30107359e-01],
       [-1.28159819e-04,  3.08318861e-03,  3.08318861e-03, ...,
         9.70155876e-02,  1.30107359e-01,  2.55743682e-01]])

In [30]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [31]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_project_ids = df_final['id'].iloc[project_indices].tolist()
    result_dict = {}
    for i, project_id in enumerate(recommended_project_ids):
        result_dict[i + 1] = project_id

    return result_dict

In [32]:
get_recommendations("dog")

{1: 3,
 2: 35,
 3: 69,
 4: 27,
 5: 7,
 6: 6,
 7: 21,
 8: 47,
 9: 29,
 10: 36,
 11: 50,
 12: 51,
 13: 45,
 14: 54,
 15: 20,
 16: 56,
 17: 31,
 18: 68,
 19: 15}

Hora de enviar los resultados de la similitud de cosenos entre vectores a la base de datos

In [36]:
send_recomendations_url = "http://localhost:3000/recommendations/recommend"

payloadRec = get_recommendations("dog")

print(type(payloadRec))

def data (payloadRec: dict):
    for i in payloadRec:
        key = i
        value = payloadRec[i]


response_recommend = requests.post(send_recomendations_url, headers=headers_projects, data=data(payloadRec))
recommendation_data = response_recommend.json()

<class 'dict'>


ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))