In [1]:
%pip install pandas
%pip install requests
%pip install numpy
%pip install tensorflow


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [ ]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()


print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow dog dog a ab a aB ab abc abc poll abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a abc a abc a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a abc abc ab abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a

In [ ]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [ ]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [ ]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

        Palabra
0           dog
1          aaaa
2        holaaa
3          siii
4          siii
..          ...
573          al
574       allpr
575          al
576        sape
577  adtgyfuyui

[578 rows x 1 columns]
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
15     cat
16     cat
17     cat
18     cat
19     cat
20     cat
21     cat
22     ggg
23     ggg
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7

In [ ]:
df3.head(15)

id                 name         description  creatorId  \
0    1                  cat                blue          2   
1    2                  dog                 red          2   
2    3                doggf                 red         56   
3    4                catff                blue         56   
4    5                lemur                grey         56   
5    6                  ppo                 ppo         56   
6    7                  ddd                 ddd         56   
7    8                sssss                 sss         56   
8    9                  sss                 sss         56   
9   10                  ggg                 ggg         56   
10  15     modified bruuhhh  modified testinggg         56   
11  17                    s                   s         56   
12  20        proyecto pepe    que tal soy sech         56   
13  21     allprojects test                sape         56   
14  24  getallprojects test                sest         56   

                   createdAt                 updatedAt  
0   2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1   2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2   2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3   2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4   2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5   2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6   2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7   2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8   2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9   2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [ ]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(578, 1)
(24, 1)
(53, 6)


In [ ]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(53, 6)


In [ ]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId
0     dog     dog   1    cat        blue          2
1    aaaa     cat   2    dog         red          2
2  holaaa     dog   3  doggf         red         56
3    siii     cat   4  catff        blue         56
4    siii     cat   5  lemur        grey         56
5     dog   doggf   6    ppo         ppo         56
6     dog     cat   7    ddd         ddd         56
7     dog     cat   8  sssss         sss         56
8     cat     cat   9    sss         sss         56
9     wow     cat  10    ggg         ggg         56

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [ ]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_features=5000)

In [ ]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [ ]:
print(type(vectorized_data))

<class 'scipy.sparse._csr.csr_matrix'>


In [ ]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [ ]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    40   41   42   43   44   45  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 46 columns]

In [ ]:
vectorized_dataframe.shape

(53, 46)

In [ ]:
from sklearn.decomposition import TruncatedSVD

In [ ]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [ ]:
reduced_data.shape

(53, 14)

In [ ]:
reduced_data

array([[-1.25741515e-06,  6.85044521e-01, -3.12507622e-01,
         5.98283124e-01, -2.73862252e-01, -1.13960968e-03,
         4.25483965e-16, -1.79357304e-16, -2.09683300e-16,
         1.16319184e-16, -2.44712127e-16, -1.24102498e-16,
        -2.12762091e-16, -2.23332780e-16],
       [ 5.29741973e-07,  4.68739346e-01, -3.13549372e-01,
        -3.60280396e-01,  7.42946384e-01,  2.33778646e-03,
         3.91423883e-16,  5.90126253e-17, -2.31264614e-16,
        -2.00922421e-16,  6.73625036e-17,  4.06235939e-16,
         3.05439243e-16,  2.16722255e-17],
       [ 5.29741973e-07,  4.68739346e-01, -3.13549372e-01,
        -3.60280396e-01,  7.42946384e-01,  2.33778646e-03,
         3.91423883e-16,  5.90126253e-17, -2.31264614e-16,
        -2.00922421e-16,  6.73625036e-17,  4.06235939e-16,
         3.05439243e-16,  2.16722255e-17],
       [-1.25741515e-06,  6.85044521e-01, -3.12507622e-01,
         5.98283124e-01, -2.73862252e-01, -1.13960968e-03,
         4.25483965e-16, -1.79357304e-16, -2.

In [ ]:
svd.explained_variance_ratio_.cumsum()

array([0.08832576, 0.1360343 , 0.18528861, 0.23146393, 0.27706151,
       0.31888824, 0.34199705, 0.36661534, 0.39120135, 0.41563162,
       0.43994783, 0.46429869, 0.48889951, 0.51293983])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(reduced_data)

In [ ]:
similarity

array([[ 1.00000000e+00,  7.65866526e-05,  7.65866526e-05, ...,
        -4.43359820e-03, -6.16509657e-03,  1.20106167e-03],
       [ 7.65866526e-05,  1.00000000e+00,  1.00000000e+00, ...,
         1.55902513e-03,  3.70725187e-03, -3.57124105e-03],
       [ 7.65866526e-05,  1.00000000e+00,  1.00000000e+00, ...,
         1.55902513e-03,  3.70725187e-03, -3.57124105e-03],
       ...,
       [-4.43359820e-03,  1.55902513e-03,  1.55902513e-03, ...,
         1.00000000e+00,  4.49687760e-02,  3.40828638e-01],
       [-6.16509657e-03,  3.70725187e-03,  3.70725187e-03, ...,
         4.49687760e-02,  1.00000000e+00,  1.17106769e-01],
       [ 1.20106167e-03, -3.57124105e-03, -3.57124105e-03, ...,
         3.40828638e-01,  1.17106769e-01,  1.00000000e+00]])

In [ ]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 9.99891537e-01,  7.65750909e-05,  7.65750909e-05, ...,
        -2.57836785e-03, -4.01207841e-03,  7.36019388e-04],
       [ 7.65750909e-05,  9.99806542e-01,  9.99806542e-01, ...,
         9.06615626e-04,  2.41247689e-03, -2.18838966e-03],
       [ 7.65750909e-05,  9.99806542e-01,  9.99806542e-01, ...,
         9.06615626e-04,  2.41247689e-03, -2.18838966e-03],
       ...,
       [-2.57836785e-03,  9.06615626e-04,  9.06615626e-04, ...,
         3.38239401e-01,  1.70206541e-02,  1.21477453e-01],
       [-4.01207841e-03,  2.41247689e-03,  2.41247689e-03, ...,
         1.70206541e-02,  4.23551441e-01,  4.67070653e-02],
       [ 7.36019388e-04, -2.18838966e-03, -2.18838966e-03, ...,
         1.21477453e-01,  4.67070653e-02,  3.75573552e-01]])

In [ ]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [ ]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_project_ids = df_final['id'].iloc[project_indices].tolist()
    result_dict = {}
    for i, project_id in enumerate(recommended_project_ids):
        result_dict[i + 1] = project_id

    return result_dict

In [ ]:
get_recommendations("dog")

{1: 3,
 2: 55,
 3: 52,
 4: 65,
 5: 36,
 6: 20,
 7: 21,
 8: 68,
 9: 33,
 10: 54,
 11: 24,
 12: 56,
 13: 67,
 14: 27,
 15: 7,
 16: 50,
 17: 51,
 18: 43,
 19: 44}

Hora de enviar los resultados de la similitud de cosenos entre vectores a la base de datos

In [ ]:
%pip install flask

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
%pip install python-dotenv

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/http://localhost:3000/recommendations/recommend', methods=['POST'])
def obtener_resultados():
    resultados = get_recommendations("dog")

    resultados_json = jsonify(resultados)

    return resultados_json

if __name__ == '__main__':
    app.run(debug=True)

Python-dotenv could not parse statement starting at line 1
Python-dotenv could not parse statement starting at line 2
Python-dotenv could not parse statement starting at line 4
Python-dotenv could not parse statement starting at line 6


 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat


SystemExit: 1

C:\Users\47295973\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3556: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
