In [36]:
%pip install pandas
%pip install requests
%pip install numpy
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [37]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [38]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()


print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow dog dog a ab a aB ab abc abc poll abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a abc a abc a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a abc abc ab abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a

In [39]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [40]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [41]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

    Palabra
0       dog
1      aaaa
2    holaaa
3      siii
4      siii
..      ...
567      ab
568       a
569      ab
570       a
571     wow

[572 rows x 1 columns]
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
15     cat
16     cat
17     cat
18     cat
19     cat
20     cat
21     cat
22     ggg
23     ggg
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7    8                                     sssss 

In [42]:
df3.head(15)

id                 name         description  creatorId  \
0    1                  cat                blue          2   
1    2                  dog                 red          2   
2    3                doggf                 red         56   
3    4                catff                blue         56   
4    5                lemur                grey         56   
5    6                  ppo                 ppo         56   
6    7                  ddd                 ddd         56   
7    8                sssss                 sss         56   
8    9                  sss                 sss         56   
9   10                  ggg                 ggg         56   
10  15     modified bruuhhh  modified testinggg         56   
11  17                    s                   s         56   
12  20        proyecto pepe    que tal soy sech         56   
13  21     allprojects test                sape         56   
14  24  getallprojects test                sest         56   

                   createdAt                 updatedAt  
0   2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1   2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2   2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3   2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4   2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5   2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6   2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7   2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8   2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9   2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [43]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(572, 1)
(24, 1)
(53, 6)


In [44]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(53, 6)


In [45]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId
0     dog     dog   1    cat        blue          2
1    aaaa     cat   2    dog         red          2
2  holaaa     dog   3  doggf         red         56
3    siii     cat   4  catff        blue         56
4    siii     cat   5  lemur        grey         56
5     dog   doggf   6    ppo         ppo         56
6     dog     cat   7    ddd         ddd         56
7     dog     cat   8  sssss         sss         56
8     cat     cat   9    sss         sss         56
9     wow     cat  10    ggg         ggg         56

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [46]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [48]:
tfidf = TfidfVectorizer(max_features=5000)

In [49]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [50]:
print(type(vectorized_data))

<class 'scipy.sparse._csr.csr_matrix'>


In [51]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [52]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    40   41   42   43   44   45  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 46 columns]

In [53]:
vectorized_dataframe.shape

(53, 46)

In [54]:
from sklearn.decomposition import TruncatedSVD

In [55]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [56]:
reduced_data.shape

(53, 14)

In [57]:
reduced_data

array([[ 1.04597624e-06,  2.56696661e-01,  7.13967733e-01,
        -2.36844470e-01,  6.06719065e-01,  1.83552825e-04,
        -3.44036412e-17, -1.10128591e-16, -2.67485358e-16,
         3.39567335e-17, -7.27582040e-17,  1.00148751e-16,
         1.22109636e-16,  1.04846809e-16],
       [ 1.13570611e-06, -1.79147197e-03,  3.04065630e-01,
         9.52456205e-01,  1.47877418e-02, -8.10685271e-04,
         3.87934200e-17, -4.33146417e-17, -1.23354407e-16,
        -2.12170933e-16,  2.36661880e-17, -1.65956133e-16,
         2.45442836e-16, -2.24411035e-18],
       [ 1.13570611e-06, -1.79147197e-03,  3.04065630e-01,
         9.52456205e-01,  1.47877418e-02, -8.10685271e-04,
         3.87934200e-17, -4.33146417e-17, -1.23354407e-16,
        -2.12170933e-16,  2.36661880e-17, -1.65956133e-16,
         2.45442836e-16, -2.24411035e-18],
       [ 1.04597624e-06,  2.56696661e-01,  7.13967733e-01,
        -2.36844470e-01,  6.06719065e-01,  1.83552825e-04,
        -3.44036412e-17, -1.10128591e-16, -2.

In [58]:
svd.explained_variance_ratio_.cumsum()

array([0.08832643, 0.13239554, 0.18135076, 0.22904495, 0.27705555,
       0.31892531, 0.34261326, 0.36720882, 0.39121294, 0.41381979,
       0.43751449, 0.46212613, 0.48655416, 0.51075616])

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

In [60]:
similarity = cosine_similarity(reduced_data)

In [61]:
similarity

array([[ 1.00000000e+00,  2.10578201e-05,  2.10578201e-05, ...,
         1.65641587e-03,  6.33678601e-04, -2.55196733e-04],
       [ 2.10578201e-05,  1.00000000e+00,  1.00000000e+00, ...,
         1.51299685e-03, -1.61997002e-03, -1.08713570e-03],
       [ 2.10578201e-05,  1.00000000e+00,  1.00000000e+00, ...,
         1.51299685e-03, -1.61997002e-03, -1.08713570e-03],
       ...,
       [ 1.65641587e-03,  1.51299685e-03,  1.51299685e-03, ...,
         1.00000000e+00,  4.21116311e-01,  9.88036584e-02],
       [ 6.33678601e-04, -1.61997002e-03, -1.61997002e-03, ...,
         4.21116311e-01,  1.00000000e+00,  1.32393345e-01],
       [-2.55196733e-04, -1.08713570e-03, -1.08713570e-03, ...,
         9.88036584e-02,  1.32393345e-01,  1.00000000e+00]])

In [62]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 9.99846460e-01,  2.10546375e-05,  2.10546375e-05, ...,
         1.03177512e-03,  2.67298234e-04, -2.14518163e-04],
       [ 2.10546375e-05,  9.99851273e-01,  9.99851273e-01, ...,
         9.42442233e-04, -6.83337210e-04, -9.13847575e-04],
       [ 2.10546375e-05,  9.99851273e-01,  9.99851273e-01, ...,
         9.42442233e-04, -6.83337210e-04, -9.13847575e-04],
       ...,
       [ 1.03177512e-03,  9.42442233e-04,  9.42442233e-04, ...,
         3.88059237e-01,  1.10665300e-01,  5.17421346e-02],
       [ 2.67298234e-04, -6.83337210e-04, -6.83337210e-04, ...,
         1.10665300e-01,  1.77959339e-01,  4.69514326e-02],
       [-2.14518163e-04, -9.13847575e-04, -9.13847575e-04, ...,
         5.17421346e-02,  4.69514326e-02,  7.06715482e-01]])

In [63]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [64]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_project_ids = df_final['id'].iloc[project_indices].tolist()
    result_dict = {}
    for i, project_id in enumerate(recommended_project_ids):
        result_dict[i + 1] = project_id

    return result_dict

In [65]:
get_recommendations("dog")

{1: 3,
 2: 52,
 3: 24,
 4: 36,
 5: 6,
 6: 7,
 7: 47,
 8: 10,
 9: 35,
 10: 53,
 11: 67,
 12: 66,
 13: 49,
 14: 62,
 15: 15,
 16: 1,
 17: 4,
 18: 8,
 19: 9}

Hora de enviar los resultados de la similitud de cosenos entre vectores a la base de datos

In [66]:
%pip install flask

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [67]:
%pip install python-dotenv

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [68]:
from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/http://localhost:3000/recommendations/recommend', methods=['POST'])
def obtener_resultados():
    resultados = get_recommendations("dog")

    resultados_json = jsonify(resultados)

    return resultados_json

if __name__ == '__main__':
    app.run(debug=True)

Python-dotenv could not parse statement starting at line 1
Python-dotenv could not parse statement starting at line 2
Python-dotenv could not parse statement starting at line 4
Python-dotenv could not parse statement starting at line 6


 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat


SystemExit: 1

C:\Users\47295973\AppData\Roaming\Python\Python311\site-packages\IPython\core\interactiveshell.py:3556: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
