In [1]:
%pip install pandas
%pip install requests
%pip install numpy
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [3]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()


print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow dog dog a ab a aB ab abc abc poll abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a abc a abc a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a abc abc ab abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a

In [4]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [5]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [6]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

        Palabra
0           dog
1          aaaa
2        holaaa
3          siii
4          siii
..          ...
573          al
574       allpr
575          al
576        sape
577  adtgyfuyui

[578 rows x 1 columns]
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
15     cat
16     cat
17     cat
18     cat
19     cat
20     cat
21     cat
22     ggg
23     ggg
24   lemur
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                    

In [7]:
df3.head(15)

id                 name         description  creatorId  \
0    1                  cat                blue          2   
1    2                  dog                 red          2   
2    3                doggf                 red         56   
3    4                catff                blue         56   
4    5                lemur                grey         56   
5    6                  ppo                 ppo         56   
6    7                  ddd                 ddd         56   
7    8                sssss                 sss         56   
8    9                  sss                 sss         56   
9   10                  ggg                 ggg         56   
10  15     modified bruuhhh  modified testinggg         56   
11  17                    s                   s         56   
12  20        proyecto pepe    que tal soy sech         56   
13  21     allprojects test                sape         56   
14  24  getallprojects test                sest         56   

                   createdAt                 updatedAt  
0   2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1   2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2   2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3   2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4   2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5   2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6   2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7   2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8   2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9   2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [8]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(578, 1)
(25, 1)
(53, 6)


In [9]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(53, 6)


In [10]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId
0     dog     dog   1    cat        blue          2
1    aaaa     cat   2    dog         red          2
2  holaaa     dog   3  doggf         red         56
3    siii     cat   4  catff        blue         56
4    siii     cat   5  lemur        grey         56
5     dog   doggf   6    ppo         ppo         56
6     dog     cat   7    ddd         ddd         56
7     dog     cat   8  sssss         sss         56
8     cat     cat   9    sss         sss         56
9     wow     cat  10    ggg         ggg         56

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [11]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
tfidf = TfidfVectorizer(max_features=5000)

In [14]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [15]:
print(type(vectorized_data))

<class 'scipy.sparse._csr.csr_matrix'>


In [16]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [17]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    40   41   42   43   44   45  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 46 columns]

In [18]:
vectorized_dataframe.shape

(53, 46)

In [19]:
from sklearn.decomposition import TruncatedSVD

In [20]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [21]:
reduced_data.shape

(53, 14)

In [22]:
reduced_data

array([[ 1.24309622e-06,  8.78856477e-01, -6.22020911e-03,
         4.20788649e-01, -2.24517259e-01,  2.89950974e-04,
        -3.12322082e-17, -1.16092799e-16,  1.37751921e-16,
        -1.65132951e-16,  7.90804923e-17, -3.20550888e-16,
        -2.48251093e-16,  2.19263936e-16],
       [-2.88523285e-06,  2.69183070e-01,  8.23402201e-01,
        -4.83787748e-01,  1.23992230e-01, -6.23064005e-04,
        -2.63858597e-19, -1.16480300e-16, -1.33964665e-16,
         4.81783633e-17,  1.96838619e-16,  4.72905174e-16,
         5.88420743e-16, -2.25920777e-16],
       [-2.88523285e-06,  2.69183070e-01,  8.23402201e-01,
        -4.83787748e-01,  1.23992230e-01, -6.23064005e-04,
        -2.63858597e-19, -1.16480300e-16, -1.33964665e-16,
         4.81783633e-17,  1.96838619e-16,  4.72905174e-16,
         5.88420743e-16, -2.25920777e-16],
       [ 1.24309622e-06,  8.78856477e-01, -6.22020911e-03,
         4.20788649e-01, -2.24517259e-01,  2.89950974e-04,
        -3.12322082e-17, -1.16092799e-16,  1.

In [23]:
svd.explained_variance_ratio_.cumsum()

array([0.08832724, 0.13682749, 0.1809994 , 0.2278379 , 0.27704317,
       0.3189231 , 0.34352685, 0.36810037, 0.39179553, 0.41566178,
       0.44017829, 0.46309872, 0.48716221, 0.5113317 ])

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
similarity = cosine_similarity(reduced_data)

In [26]:
similarity

array([[ 1.00000000e+00,  4.05853848e-05,  4.05853848e-05, ...,
         5.12086649e-03,  2.72501308e-03,  6.38006444e-03],
       [ 4.05853848e-05,  1.00000000e+00,  1.00000000e+00, ...,
         3.36472678e-03, -9.71828543e-04, -8.15496803e-03],
       [ 4.05853848e-05,  1.00000000e+00,  1.00000000e+00, ...,
         3.36472678e-03, -9.71828543e-04, -8.15496803e-03],
       ...,
       [ 5.12086649e-03,  3.36472678e-03,  3.36472678e-03, ...,
         1.00000000e+00, -2.76271723e-01,  5.66240528e-01],
       [ 2.72501308e-03, -9.71828543e-04, -9.71828543e-04, ...,
        -2.76271723e-01,  1.00000000e+00, -2.02881727e-01],
       [ 6.38006444e-03, -8.15496803e-03, -8.15496803e-03, ...,
         5.66240528e-01, -2.02881727e-01,  1.00000000e+00]])

In [27]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 9.99898569e-01,  4.05808053e-05,  4.05808053e-05, ...,
         2.92346365e-03,  1.54850886e-03,  3.14241770e-03],
       [ 4.05808053e-05,  9.99875757e-01,  9.99875757e-01, ...,
         1.92087496e-03, -5.52242464e-04, -4.01657755e-03],
       [ 4.05808053e-05,  9.99875757e-01,  9.99875757e-01, ...,
         1.92087496e-03, -5.52242464e-04, -4.01657755e-03],
       ...,
       [ 2.92346365e-03,  1.92087496e-03,  1.92087496e-03, ...,
         3.25951169e-01, -8.96354567e-02,  1.59234840e-01],
       [ 1.54850886e-03, -5.52242464e-04, -5.52242464e-04, ...,
        -8.96354567e-02,  3.22949233e-01, -5.67898779e-02],
       [ 3.14241770e-03, -4.01657755e-03, -4.01657755e-03, ...,
         1.59234840e-01, -5.67898779e-02,  2.42617290e-01]])

In [28]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [29]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_projects = [{"projectId": int(df_final['id'].iloc[i])} for i in project_indices]
    """recommended_project_ids = df_final['id'].iloc[project_indices].tolist()
    result_projects = [recommended_project_ids] """
    
    return recommended_projects

In [30]:
get_recommendations("dog")

[{'projectId': 3},
 {'projectId': 25},
 {'projectId': 45},
 {'projectId': 66},
 {'projectId': 67},
 {'projectId': 33},
 {'projectId': 55},
 {'projectId': 7},
 {'projectId': 36},
 {'projectId': 53},
 {'projectId': 65},
 {'projectId': 54},
 {'projectId': 35},
 {'projectId': 10},
 {'projectId': 50},
 {'projectId': 51},
 {'projectId': 20},
 {'projectId': 21},
 {'projectId': 56}]

In [31]:
print(type(get_recommendations("dog")[0]))

<class 'dict'>


Hora de enviar los resultados de la similitud de cosenos entre vectores a la base de datos

In [35]:
import json

url = "http://localhost:3000/recommendations/recommend"

datos_json = {
    "id": 56,
    "projectsWithAffinities": get_recommendations("cat")
} 

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}


print(datos_json)

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

print("Hola")
respuesta = requests.post(url, data=json.dumps(datos_json), headers=encabezado)


print("Hola")
if respuesta.status_code == 200:
    print('Solicitud exitosa. Respuesta del servidor:')
    print(respuesta.json())
else:
    print(f'Error en la solicitud. Código de estado: {respuesta.status_code}')
    print(respuesta.text)

{'id': 56, 'projectsWithAffinities': [{'projectId': 4}, {'projectId': 69}, {'projectId': 67}, {'projectId': 29}, {'projectId': 54}, {'projectId': 7}, {'projectId': 65}, {'projectId': 68}, {'projectId': 5}, {'projectId': 15}, {'projectId': 52}, {'projectId': 24}, {'projectId': 49}, {'projectId': 43}, {'projectId': 44}, {'projectId': 60}, {'projectId': 8}, {'projectId': 9}, {'projectId': 2}]}
Hola
Hola
Error en la solicitud. Código de estado: 404
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /recommendations/recommend</pre>
</body>
</html>

