#Acordate de agarrar con el github desktop el brunch de BACK y ponerlo en la PC de casa para despues, correr el server en el localhost:3000 y poder utilizar este codigo

In [227]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [228]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()

print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow 
dog cat dog cat cat doggf cat cat cat cat cat cat cat cat uuuuuu
[{'id': 1, 'name': 'cat', 'description': 'blue', 'creatorId': 2, 'createdAt': '2023-10-30T13:39:26.619Z', 'updatedAt': '2023-10-30T13:39:26.619Z'}, {'id': 2, 'name': 'dog', 'description': 'red', 'creatorId': 2, 'createdAt': '2023-10-30T13:39:46.698Z', 'updatedAt': '2023-10-30T13:39:46.698Z'}, {'id': 3, 'name': 'doggf', 'description': 'red', 'creatorId': 56, 'createdAt': '2023-11-01T21:16:53.796Z', 'updatedAt': '2023-11-03T01:05:23.711Z'}, {'id': 4, 'name': 'catff', 'description': 'blue', 'creatorId': 56, 'createdAt': '2023-11-01T21:17:02.209Z', 'updatedAt': '2023-11-03T01:06:51.653Z'}, {'id': 5, 'name': 'lemur', 'description': 'grey', 'creatorId': 56, 'createdAt': '2023-11-01T21:17:15.554Z', 'updatedAt': '2023-11-01T21:17:15.554Z'}, {'id': 6, 'name': 'ppo', 'description': 'ppo', 'creatorId': 56, 'createdAt': '2023-11-01T22:23:22.617Z', 'updatedAt': '2023-11-01T22:23:22.617Z'}

In [229]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [230]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [231]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

  Palabra
0     dog
1    aaaa
2  holaaa
3    siii
4    siii
5     dog
6     dog
7     dog
8     cat
9     wow
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7    8                                     sssss   
8    9                                       sss   
9   10                                       ggg   
10  15                          modified bruuhhh  

In [232]:
df3.head(15)

id                 name         description  creatorId  \
0    1                  cat                blue          2   
1    2                  dog                 red          2   
2    3                doggf                 red         56   
3    4                catff                blue         56   
4    5                lemur                grey         56   
5    6                  ppo                 ppo         56   
6    7                  ddd                 ddd         56   
7    8                sssss                 sss         56   
8    9                  sss                 sss         56   
9   10                  ggg                 ggg         56   
10  15     modified bruuhhh  modified testinggg         56   
11  17                    s                   s         56   
12  20        proyecto pepe    que tal soy sech         56   
13  21     allprojects test                sape         56   
14  24  getallprojects test                sest         56   

                   createdAt                 updatedAt  
0   2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1   2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2   2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3   2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4   2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5   2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6   2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7   2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8   2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9   2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [233]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(10, 1)
(15, 1)
(45, 6)


In [234]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(15, 6)


In [235]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId
0     dog     dog   1    cat        blue          2
1    aaaa     cat   2    dog         red          2
2  holaaa     dog   3  doggf         red         56
3    siii     cat   4  catff        blue         56
4    siii     cat   5  lemur        grey         56
5     dog   doggf   6    ppo         ppo         56
6     dog     cat   7    ddd         ddd         56
7     dog     cat   8  sssss         sss         56
8     cat     cat   9    sss         sss         56
9     wow     cat  10    ggg         ggg         56

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [236]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [237]:
tfidf = TfidfVectorizer(max_features=5000)

In [238]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [239]:
print(type(vectorized_data))

<class 'scipy.sparse.csr.csr_matrix'>


In [240]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [241]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [242]:
vectorized_dataframe.shape

(15, 15)

In [243]:
from sklearn.decomposition import TruncatedSVD

In [245]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [246]:
reduced_data.shape

(15, 14)

In [247]:
reduced_data

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -4.47213595e-01,  8.94427191e-01,
        -2.22044605e-16, -2.77555756e-16,  0.00000000e+00,
         9.36750677e-17,  1.38777878e-17,  8.32667268e-17,
        -2.77555756e-17, -3.88578059e-15,  1.13655081e-17,
        -1.58049960e-17,  3.83630111e-18],
       [ 0.00000000e+00, -4.47213595e-01,  8.94427191e-01,
        -2.22044605e-16, -2.77555756e-16,  0.00000000e+00,
         9.36750677e-17,  1.38777878e-17,  8.32667268e-17,
        -2.77555756e-17, -3.88578059e-15,  1.13655081e-17,
        -1.58049960e-17,  3.83630111e-18],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.

In [248]:
svd.explained_variance_ratio_.cumsum()

array([0.13684211, 0.29052632, 0.41052632, 0.48860623, 0.5596526 ,
       0.62696168, 0.70532162, 0.77171085, 0.85056772, 0.92773123,
       1.        , 1.        , 1.        , 1.        ])

In [249]:
from sklearn.metrics.pairwise import cosine_similarity

In [250]:
similarity = cosine_similarity(reduced_data)

In [251]:
similarity

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00, -5.58190393e-17,  3.58215309e-17,
         1.11098726e-16, -2.06356151e-16, -2.06356151e-16,
        -1.54750210e-16,  7.42827929e-17,  0.00000000e+00,
        -9.82562386e-17,  1.16446966e-18, -1.04203032e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00, -5.58190393e-17,  3.58215309e-17,
         1.11098726e-16, -2.06356151e-16, -2.06356151e-16,
        -1.54750210e-16,  7.42827929e-17,  0.00000000e+00,
        -9.82562386e-17,  1.16446966e-18, -1.04203032e-16],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000

In [252]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00, -5.58190393e-17,  3.58215309e-17,
         1.11098726e-16, -2.00495683e-16, -2.00495683e-16,
        -1.54750210e-16,  7.42827929e-17,  0.00000000e+00,
        -9.82562386e-17,  1.16446966e-18, -1.04203032e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00, -5.58190393e-17,  3.58215309e-17,
         1.11098726e-16, -2.00495683e-16, -2.00495683e-16,
        -1.54750210e-16,  7.42827929e-17,  0.00000000e+00,
        -9.82562386e-17,  1.16446966e-18, -1.04203032e-16],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000

In [253]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [254]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    movie_indices = [i[0] for i in sim_scores]

    recommended_projects = df_final['name'].iloc[movie_indices].tolist()
    result_dict = {}
    for i, movie in enumerate(recommended_projects):
        result_dict[i + 1] = movie

    return result_dict

In [255]:
get_recommendations("dog")

{1: 'doggf',
 2: 'ddd',
 3: 'modified bruuhhh',
 4: 'ppo',
 5: 'allprojects test',
 6: 'cat',
 7: 'catff',
 8: 's',
 9: 'lemur',
 10: 'proyecto pepe',
 11: 'getallprojects test',
 12: 'ggg',
 13: 'sssss',
 14: 'sss'}