#Acordate de agarrar con el github desktop el brunch de BACK y ponerlo en la PC de casa para despues, correr el server en el localhost:3000 y poder utilizar este codigo

In [17]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [18]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()

print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow dog dog 
dog cat dog cat cat doggf cat cat cat cat cat cat cat cat uuuuuu cat cat cat cat cat cat cat ggg ggg
[{'id': 1, 'name': 'cat', 'description': 'blue', 'creatorId': 2, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023-10-30T13:39:26.619Z', 'updatedAt': '2023-10-30T13:39:26.619Z'}, {'id': 2, 'name': 'dog', 'description': 'red', 'creatorId': 2, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023-10-30T13:39:46.698Z', 'updatedAt': '2023-10-30T13:39:46.698Z'}, {'id': 3, 'name': 'doggf', 'description': 'red', 'creatorId': 56, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023-11-01T21:16:53.796Z', 'updatedAt': '2023-11-03T01:05:23.711Z'}, {'id': 4, 'name': 'catff', 'description': 'blue', 'creatorId': 56, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023-11-01T21:17:02.209Z', 'updatedAt': '2023-11-03T01:06:51.653Z'}, {'id': 5, 'name': 'lemur', 'description': 'grey', 'creatorId': 56, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023-11-01

In [19]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'statusId': 1,
 'maxMembers': 5,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [20]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [21]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

   Palabra
0      dog
1     aaaa
2   holaaa
3     siii
4     siii
5      dog
6      dog
7      dog
8      cat
9      wow
10     dog
11     dog
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
15     cat
16     cat
17     cat
18     cat
19     cat
20     cat
21     cat
22     ggg
23     ggg
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7    8                                     sssss   
8    9                

In [22]:
df3.head(15)

id                 name         description  creatorId  statusId  \
0    1                  cat                blue          2         1   
1    2                  dog                 red          2         1   
2    3                doggf                 red         56         1   
3    4                catff                blue         56         1   
4    5                lemur                grey         56         1   
5    6                  ppo                 ppo         56         1   
6    7                  ddd                 ddd         56         1   
7    8                sssss                 sss         56         1   
8    9                  sss                 sss         56         1   
9   10                  ggg                 ggg         56         1   
10  15     modified bruuhhh  modified testinggg         56         1   
11  17                    s                   s         56         1   
12  20        proyecto pepe    que tal soy sech         56         1   
13  21     allprojects test                sape         56         1   
14  24  getallprojects test                sest         56         1   

    maxMembers                 createdAt                 updatedAt  
0            5  2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1            5  2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2            5  2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3            5  2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4            5  2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5            5  2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6            5  2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7            5  2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8            5  2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9            5  2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10           5  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11           5  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12           5  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13           5  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14           5  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [23]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(12, 1)
(24, 1)
(48, 8)


In [24]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(24, 8)


In [25]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId  statusId  maxMembers
0     dog     dog   1    cat        blue          2         1           5
1    aaaa     cat   2    dog         red          2         1           5
2  holaaa     dog   3  doggf         red         56         1           5
3    siii     cat   4  catff        blue         56         1           5
4    siii     cat   5  lemur        grey         56         1           5
5     dog   doggf   6    ppo         ppo         56         1           5
6     dog     cat   7    ddd         ddd         56         1           5
7     dog     cat   8  sssss         sss         56         1           5
8     cat     cat   9    sss         sss         56         1           5
9     wow     cat  10    ggg         ggg         56         1           5

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [27]:
tfidf = TfidfVectorizer(max_features=5000)

In [28]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [29]:
print(type(vectorized_data))

<class 'scipy.sparse.csr.csr_matrix'>


In [30]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [31]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   16   17   18   19  \
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  0.0   
3  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    20   21   22   23   24   25  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 26 columns]

In [32]:
vectorized_dataframe.shape

(24, 26)

In [33]:
from sklearn.decomposition import TruncatedSVD

In [34]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [35]:
reduced_data.shape

(24, 14)

In [36]:
reduced_data

array([[-3.28282229e-17,  3.33378341e-16,  1.00000000e+00,
         5.92390567e-17, -7.04154625e-18,  6.05436920e-19,
        -1.24107256e-18, -2.59134532e-18,  8.98142825e-19,
        -8.04988646e-19,  3.35657665e-18, -2.73939765e-18,
         6.20815530e-19, -1.06315986e-18],
       [-1.96192392e-01,  9.80565421e-01, -3.65846834e-16,
         2.78326735e-17,  1.51428647e-17,  5.47484193e-17,
         2.09157341e-17, -5.50125812e-17,  9.85987958e-17,
         6.05282955e-17, -6.21687404e-17,  4.83450927e-17,
         1.87436756e-16, -7.70784943e-17],
       [-1.96192392e-01,  9.80565421e-01, -3.65846834e-16,
         2.78326735e-17,  1.51428647e-17,  5.47484193e-17,
         2.09157341e-17, -5.50125812e-17,  9.85987958e-17,
         6.05282955e-17, -6.21687404e-17,  4.83450927e-17,
         1.87436756e-16, -7.70784943e-17],
       [-3.28282229e-17,  3.33378341e-16,  1.00000000e+00,
         5.92390567e-17, -7.04154625e-18,  6.05436920e-19,
        -1.24107256e-18, -2.59134532e-18,  8.

In [37]:
svd.explained_variance_ratio_.cumsum()

array([0.10030625, 0.1938326 , 0.2907489 , 0.34361001, 0.39483901,
       0.44751235, 0.49670531, 0.54607836, 0.5955448 , 0.64670974,
       0.69875243, 0.74892533, 0.79804956, 0.8508767 ])

In [38]:
from sklearn.metrics.pairwise import cosine_similarity

In [39]:
similarity = cosine_similarity(reduced_data)

In [40]:
similarity

array([[ 1.00000000e+00, -3.25069124e-17, -3.25069124e-17,
         1.00000000e+00, -2.17735808e-17,  7.40954078e-18,
        -6.66623086e-18, -8.24165421e-18, -8.24165421e-18,
        -9.07948026e-18,  4.23055742e-17,  0.00000000e+00,
        -6.19936277e-17, -2.91014517e-17,  1.04937209e-17,
         2.73395332e-17,  3.78838501e-17,  0.00000000e+00,
        -5.95914065e-17,  0.00000000e+00, -7.85659816e-18,
         1.37141909e-17,  5.06230722e-17,  0.00000000e+00],
       [-3.25069124e-17,  1.00000000e+00,  1.00000000e+00,
        -3.25069124e-17, -5.68217890e-17,  7.49778512e-17,
        -7.20210741e-18,  1.07196048e-16,  1.07196048e-16,
         1.46714675e-17,  9.10792966e-17,  0.00000000e+00,
        -2.19147222e-17,  9.71857723e-17, -6.93321150e-18,
         8.95814855e-18,  3.06911583e-17,  0.00000000e+00,
         4.76084210e-17,  0.00000000e+00,  3.21027342e-17,
        -5.43658189e-17, -3.23311153e-16,  0.00000000e+00],
       [-3.25069124e-17,  1.00000000e+00,  1.00000000e

In [41]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 1.00000000e+00, -3.25069124e-17, -3.25069124e-17,
         1.00000000e+00, -1.89230079e-17,  6.50834725e-18,
        -6.05715322e-18, -8.24165421e-18, -8.24165421e-18,
        -6.58119792e-18,  3.87965659e-17,  0.00000000e+00,
        -5.93518270e-17, -2.47627691e-17,  9.35245355e-18,
         1.71129293e-17,  3.45010657e-17,  0.00000000e+00,
        -5.68056665e-17,  0.00000000e+00, -7.62266142e-18,
         1.32185551e-17,  4.65612421e-17,  0.00000000e+00],
       [-3.25069124e-17,  1.00000000e+00,  1.00000000e+00,
        -3.25069124e-17, -4.93827438e-17,  6.58585877e-17,
        -6.54406801e-18,  1.11595663e-16,  1.11595663e-16,
         1.06345109e-17,  8.35247835e-17,  0.00000000e+00,
        -2.09808467e-17,  8.26965218e-17, -6.17917505e-18,
         5.60727070e-18,  2.79506351e-17,  0.00000000e+00,
         4.53828537e-17,  0.00000000e+00,  3.11468486e-17,
        -5.24010183e-17, -2.97369721e-16,  0.00000000e+00],
       [-3.25069124e-17,  1.00000000e+00,  1.00000000e

In [42]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [43]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    movie_indices = [i[0] for i in sim_scores]

    recommended_projects = df_final['name'].iloc[movie_indices].tolist()
    result_dict = {}
    for i, movie in enumerate(recommended_projects):
        result_dict[i + 1] = movie

    return result_dict

In [44]:
get_recommendations("dog")

{1: 'doggf',
 2: 'sssss',
 3: 'sss',
 4: 'modified bruuhhh',
 5: 'allprojects test',
 6: 'ppo',
 7: 'proyecto FUNCA!!!!!!!!!!!!!!!!!!!!!!!!!!',
 8: 'pp',
 9: 'pollogange',
 10: 'ggg',
 11: 'otro test',
 12: 's',
 13: 'cache de mierda',
 14: 'mentira no funca nada',
 15: 'ninjafornte',
 16: 'getallprojects test',
 17: 'ddd',
 18: 'proyecto pepe',
 19: 'cat'}