In [121]:
%pip install pandas
%pip install requests
%pip install numpy
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [122]:
import pandas as pd
import requests


In [123]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "56"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()


print(search_history_data)
print(visit_history_data)
print(all_projects_data)

dog aaaa holaaa siii siii dog dog dog cat wow dog dog a ab a aB ab abc abc poll abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a abc a abc a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a abc abc ab abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a

In [124]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'statusId': 1,
 'maxMembers': 5,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [125]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'AllPalabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [126]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

        Palabra
0           dog
1          aaaa
2        holaaa
3          siii
4          siii
..          ...
573          al
574       allpr
575          al
576        sape
577  adtgyfuyui

[578 rows x 1 columns]
--------------------------------------------

   AllPalabra
0         dog
1         cat
2         dog
3         cat
4         cat
5       doggf
6         cat
7         cat
8         cat
9         cat
10        cat
11        cat
12        cat
13        cat
14     uuuuuu
15        cat
16        cat
17        cat
18        cat
19        cat
20        cat
21        cat
22        ggg
23        ggg
24      lemur
25   pollines
26      lemur
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                  

In [127]:
df3.head(15)

id                 name         description  creatorId  statusId  \
0    1                  cat                blue          2         1   
1    2                  dog                 red          2         1   
2    3                doggf                 red         56         1   
3    4                catff                blue         56         1   
4    5                lemur                grey         56         1   
5    6                  ppo                 ppo         56         1   
6    7                  ddd                 ddd         56         1   
7    8                sssss                 sss         56         1   
8    9                  sss                 sss         56         1   
9   10                  ggg                 ggg         56         1   
10  15     modified bruuhhh  modified testinggg         56         1   
11  17                    s                   s         56         1   
12  20        proyecto pepe    que tal soy sech         56         1   
13  21     allprojects test                sape         56         1   
14  24  getallprojects test                sest         56         1   

    maxMembers                 createdAt                 updatedAt  
0            5  2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1            5  2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2            5  2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3            5  2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4            5  2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5            5  2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6            5  2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7            5  2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8            5  2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9            5  2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10           5  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11           5  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12           5  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13           5  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14           5  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [128]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(578, 1)
(27, 1)
(53, 8)


In [156]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)
df_final = df_final.drop(['statusId'], axis=1)
df_final = df_final.drop(['maxMembers'], axis=1)

print(df_final.shape)

(53, 6)


In [157]:
df_final.head(10)

Palabra AllPalabra  id   name description  creatorId
0     dog        dog   1    cat        blue          2
1    aaaa        cat   2    dog         red          2
2  holaaa        dog   3  doggf         red         56
3    siii        cat   4  catff        blue         56
4    siii        cat   5  lemur        grey         56
5     dog      doggf   6    ppo         ppo         56
6     dog        cat   7    ddd         ddd         56
7     dog        cat   8  sssss         sss         56
8     cat        cat   9    sss         sss         56
9     wow        cat  10    ggg         ggg         56

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [131]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [132]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [133]:
tfidf = TfidfVectorizer(max_features=5000)

In [134]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [135]:
print(type(vectorized_data))

<class 'scipy.sparse._csr.csr_matrix'>


In [136]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [137]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    40   41   42   43   44   45  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 46 columns]

In [138]:
vectorized_dataframe.shape

(53, 46)

In [139]:
from sklearn.decomposition import TruncatedSVD

In [140]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [141]:
reduced_data.shape

(53, 14)

In [142]:
reduced_data

array([[ 4.22442466e-07, -4.39122702e-01, -5.07128944e-01,
         7.23844023e-01,  1.61055539e-01, -5.34287371e-04,
         3.06105453e-16, -8.61534029e-17, -6.99844015e-17,
         3.10865472e-16,  6.87275567e-17, -1.95900055e-16,
         1.08753409e-16, -2.11398296e-17],
       [ 5.96669379e-07, -1.00275548e-01,  8.36042628e-01,
         4.63487221e-01,  2.75811482e-01, -1.31572828e-05,
         4.08760489e-17,  2.69627153e-16, -3.61151214e-17,
         1.83728455e-16, -2.47837103e-17, -6.34116753e-17,
         1.49200216e-17, -1.26476545e-16],
       [ 5.96669379e-07, -1.00275548e-01,  8.36042628e-01,
         4.63487221e-01,  2.75811482e-01, -1.31572828e-05,
         4.08760489e-17,  2.69627153e-16, -3.61151214e-17,
         1.83728455e-16, -2.47837103e-17, -6.34116753e-17,
         1.49200216e-17, -1.26476545e-16],
       [ 4.22442466e-07, -4.39122702e-01, -5.07128944e-01,
         7.23844023e-01,  1.61055539e-01, -5.34287371e-04,
         3.06105453e-16, -8.61534029e-17, -6.

In [143]:
svd.explained_variance_ratio_.cumsum()

array([0.0883275 , 0.13647394, 0.18572899, 0.23011173, 0.27711176,
       0.31897826, 0.34238427, 0.36691771, 0.39125007, 0.41408426,
       0.43863042, 0.46325582, 0.48765105, 0.51227073])

In [144]:
from sklearn.metrics.pairwise import cosine_similarity

In [145]:
similarity = cosine_similarity(reduced_data)

In [146]:
similarity

array([[ 1.00000000e+00, -3.47194725e-05, -3.47194725e-05, ...,
         5.20802722e-03, -4.20118568e-03,  1.11600451e-03],
       [-3.47194725e-05,  1.00000000e+00,  1.00000000e+00, ...,
         4.25997490e-03,  1.22240576e-03, -2.49997390e-03],
       [-3.47194725e-05,  1.00000000e+00,  1.00000000e+00, ...,
         4.25997490e-03,  1.22240576e-03, -2.49997390e-03],
       ...,
       [ 5.20802722e-03,  4.25997490e-03,  4.25997490e-03, ...,
         1.00000000e+00,  4.49248188e-01,  2.31680841e-01],
       [-4.20118568e-03,  1.22240576e-03,  1.22240576e-03, ...,
         4.49248188e-01,  1.00000000e+00,  3.89445853e-01],
       [ 1.11600451e-03, -2.49997390e-03, -2.49997390e-03, ...,
         2.31680841e-01,  3.89445853e-01,  1.00000000e+00]])

In [147]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 9.99897855e-01, -3.47162209e-05, -3.47162209e-05, ...,
         3.14432208e-03, -2.49256159e-03,  7.35207232e-04],
       [-3.47162209e-05,  9.99914839e-01,  9.99914839e-01, ...,
         2.57196177e-03,  7.25258952e-04, -1.64695974e-03],
       [-3.47162209e-05,  9.99914839e-01,  9.99914839e-01, ...,
         2.57196177e-03,  7.25258952e-04, -1.64695974e-03],
       ...,
       [ 3.14432208e-03,  2.57196177e-03,  2.57196177e-03, ...,
         3.64545651e-01,  1.60937962e-01,  9.21577968e-02],
       [-2.49256159e-03,  7.25258952e-04,  7.25258952e-04, ...,
         1.60937962e-01,  3.52040319e-01,  1.52233169e-01],
       [ 7.35207232e-04, -1.64695974e-03, -1.64695974e-03, ...,
         9.21577968e-02,  1.52233169e-01,  4.34042249e-01]])

In [148]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [149]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_projects = [{"projectId": int(df_final['id'].iloc[i])} for i in project_indices]
    
    return recommended_projects

In [150]:
get_recommendations("dog")

[{'projectId': 3},
 {'projectId': 45},
 {'projectId': 67},
 {'projectId': 55},
 {'projectId': 32},
 {'projectId': 24},
 {'projectId': 49},
 {'projectId': 15},
 {'projectId': 68},
 {'projectId': 21},
 {'projectId': 29},
 {'projectId': 27},
 {'projectId': 43},
 {'projectId': 44},
 {'projectId': 60},
 {'projectId': 17},
 {'projectId': 28},
 {'projectId': 30},
 {'projectId': 34}]

In [151]:
print(type(get_recommendations("dog")[0]))

<class 'dict'>


Hora de enviar los resultados de la similitud de cosenos entre vectores a la base de datos

In [152]:
import json

url = "http://localhost:3000/recommendations/recommend"

datos_json = {
    "id": 55,
    "projectsWithAffinities": get_recommendations("dog")
}

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

print(datos_json)

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

print("Hola")
respuesta = requests.post(url, data=json.dumps(datos_json), headers=encabezado)


print("Hola")
if respuesta.status_code == 200:
    print('Solicitud exitosa. Respuesta del servidor:')
    print(respuesta.json())
else:
    print(f'Error en la solicitud. Código de estado: {respuesta.status_code}')
    print(respuesta.text)

{'id': 55, 'projectsWithAffinities': [{'projectId': 3}, {'projectId': 45}, {'projectId': 67}, {'projectId': 55}, {'projectId': 32}, {'projectId': 24}, {'projectId': 49}, {'projectId': 15}, {'projectId': 68}, {'projectId': 21}, {'projectId': 29}, {'projectId': 27}, {'projectId': 43}, {'projectId': 44}, {'projectId': 60}, {'projectId': 17}, {'projectId': 28}, {'projectId': 30}, {'projectId': 34}]}
Hola
Hola
Solicitud exitosa. Respuesta del servidor:
{'message': 'created recommendations'}


In [160]:
df_history = df_final.drop(["id"], axis=1)
df_history = df_history.drop(["name"], axis=1)
df_history = df_history.drop(["creatorId"], axis=1)
df_history = df_history.drop(["AllPalabra"], axis=1)

print(df_history.head(5))

  Palabra description
0     dog        blue
1    aaaa         red
2  holaaa         red
3    siii        blue
4    siii        grey


In [161]:
def recommend_projects():
    
    df_history['Palabra'] = df_history['Palabra'].astype(str)
    df_history['description'] = df_history['description'].astype(str)

    tfidf_vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf_vectorizer.fit_transform(df_history['description'], df_history['Palabra'])

    # Obtener las similitudes coseno entre el historial de búsqueda y las descripciones de los proyectos
    cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)

    # Recomendar proyectos para la última búsqueda en el historial
    search_similarity = cosine_similarities[-1]
    related_projects_indices = search_similarity.argsort()[:-1][::-1]
    recommended_projects = df_final.iloc[related_projects_indices][['id', 'name', 'description', 'creatorId']]

    return recommended_projects

In [162]:
recommendations = recommend_projects()
print("Proyectos recomendados:")
print(recommendations)

Proyectos recomendados:
    id                                      name  \
25  36                                    gagner   
23  34                               ninjafornte   
22  33                          nachao vigiialte   
21  32                                      papu   
20  31                                        pp   
19  30                     mentira no funca nada   
18  29  proyecto FUNCA!!!!!!!!!!!!!!!!!!!!!!!!!!   
17  28                           cache de mierda   
16  27                                pollogange   
15  25                                 otro test   
14  24                       getallprojects test   
13  21                          allprojects test   
12  20                             proyecto pepe   
11  17                                         s   
10  15                          modified bruuhhh   
9   10                                       ggg   
8    9                                       sss   
7    8                                  