In [6]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [15]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}


print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow dog dog a ab a aB ab abc abc poll abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a abc a abc a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a abc abc ab abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a

In [16]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>
<class 'dict'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'statusId': 1,
 'maxMembers': 5,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [17]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [18]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

    Palabra
0       dog
1      aaaa
2    holaaa
3      siii
4      siii
..      ...
566      aa
567      ab
568       a
569      ab
570       a

[571 rows x 1 columns]
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
15     cat
16     cat
17     cat
18     cat
19     cat
20     cat
21     cat
22     ggg
23     ggg
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7    8                                     sssss 

In [19]:
df3.head(15)

id                 name         description  creatorId  statusId  \
0    1                  cat                blue          2         1   
1    2                  dog                 red          2         1   
2    3                doggf                 red         56         1   
3    4                catff                blue         56         1   
4    5                lemur                grey         56         1   
5    6                  ppo                 ppo         56         1   
6    7                  ddd                 ddd         56         1   
7    8                sssss                 sss         56         1   
8    9                  sss                 sss         56         1   
9   10                  ggg                 ggg         56         1   
10  15     modified bruuhhh  modified testinggg         56         1   
11  17                    s                   s         56         1   
12  20        proyecto pepe    que tal soy sech         56         1   
13  21     allprojects test                sape         56         1   
14  24  getallprojects test                sest         56         1   

    maxMembers                 createdAt                 updatedAt  
0            5  2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1            5  2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2            5  2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3            5  2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4            5  2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5            5  2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6            5  2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7            5  2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8            5  2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9            5  2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10           5  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11           5  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12           5  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13           5  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14           5  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [20]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(571, 1)
(24, 1)
(53, 8)


In [21]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(53, 8)


In [22]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId  statusId  maxMembers
0     dog     dog   1    cat        blue          2         1           5
1    aaaa     cat   2    dog         red          2         1           5
2  holaaa     dog   3  doggf         red         56         1           5
3    siii     cat   4  catff        blue         56         1           5
4    siii     cat   5  lemur        grey         56         1           5
5     dog   doggf   6    ppo         ppo         56         1           5
6     dog     cat   7    ddd         ddd         56         1           5
7     dog     cat   8  sssss         sss         56         1           5
8     cat     cat   9    sss         sss         56         1           5
9     wow     cat  10    ggg         ggg         56         1           5

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
tfidf = TfidfVectorizer(max_features=5000)

In [26]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [27]:
print(type(vectorized_data))

<class 'scipy.sparse.csr.csr_matrix'>


In [28]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [29]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    40   41   42   43   44   45  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 46 columns]

In [30]:
vectorized_dataframe.shape

(53, 46)

In [31]:
from sklearn.decomposition import TruncatedSVD

In [32]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [33]:
reduced_data.shape

(53, 14)

In [36]:
reduced_data

array([[-3.28282229e-17,  3.33378341e-16,  1.00000000e+00,
         5.92390567e-17, -7.04154625e-18,  6.05436920e-19,
        -1.24107256e-18, -2.59134532e-18,  8.98142825e-19,
        -8.04988646e-19,  3.35657665e-18, -2.73939765e-18,
         6.20815530e-19, -1.06315986e-18],
       [-1.96192392e-01,  9.80565421e-01, -3.65846834e-16,
         2.78326735e-17,  1.51428647e-17,  5.47484193e-17,
         2.09157341e-17, -5.50125812e-17,  9.85987958e-17,
         6.05282955e-17, -6.21687404e-17,  4.83450927e-17,
         1.87436756e-16, -7.70784943e-17],
       [-1.96192392e-01,  9.80565421e-01, -3.65846834e-16,
         2.78326735e-17,  1.51428647e-17,  5.47484193e-17,
         2.09157341e-17, -5.50125812e-17,  9.85987958e-17,
         6.05282955e-17, -6.21687404e-17,  4.83450927e-17,
         1.87436756e-16, -7.70784943e-17],
       [-3.28282229e-17,  3.33378341e-16,  1.00000000e+00,
         5.92390567e-17, -7.04154625e-18,  6.05436920e-19,
        -1.24107256e-18, -2.59134532e-18,  8.

In [34]:
svd.explained_variance_ratio_.cumsum()

array([0.08832658, 0.13494275, 0.17946696, 0.22828838, 0.27698651,
       0.31883625, 0.34346485, 0.36734947, 0.39120215, 0.41582868,
       0.44038326, 0.46497932, 0.48856091, 0.51264212])

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
similarity = cosine_similarity(reduced_data)

In [37]:
similarity

array([[ 1.00000000e+00, -1.53043623e-05, -1.53043623e-05, ...,
         1.88172210e-03,  5.65972253e-03, -2.40643099e-03],
       [-1.53043623e-05,  1.00000000e+00,  1.00000000e+00, ...,
         3.60123193e-03,  1.72355173e-03,  1.04944572e-02],
       [-1.53043623e-05,  1.00000000e+00,  1.00000000e+00, ...,
         3.60123193e-03,  1.72355173e-03,  1.04944572e-02],
       ...,
       [ 1.88172210e-03,  3.60123193e-03,  3.60123193e-03, ...,
         1.00000000e+00,  3.38827145e-01,  2.79940960e-04],
       [ 5.65972253e-03,  1.72355173e-03,  1.72355173e-03, ...,
         3.38827145e-01,  1.00000000e+00, -1.44155237e-01],
       [-2.40643099e-03,  1.04944572e-02,  1.04944572e-02, ...,
         2.79940960e-04, -1.44155237e-01,  1.00000000e+00]])

In [38]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 9.99818236e-01, -1.53024665e-05, -1.53024665e-05, ...,
         6.98265538e-04,  3.10413710e-03, -9.52231240e-04],
       [-1.53024665e-05,  9.99934021e-01,  9.99934021e-01, ...,
         1.33641506e-03,  9.45355648e-04,  4.15292548e-03],
       [-1.53024665e-05,  9.99934021e-01,  9.99934021e-01, ...,
         1.33641506e-03,  9.45355648e-04,  4.15292548e-03],
       ...,
       [ 6.98265538e-04,  1.33641506e-03,  1.33641506e-03, ...,
         1.37723862e-01,  6.89712379e-02,  4.11130343e-05],
       [ 3.10413710e-03,  9.45355648e-04,  9.45355648e-04, ...,
         6.89712379e-02,  3.00864160e-01, -3.12913383e-02],
       [-9.52231240e-04,  4.15292548e-03,  4.15292548e-03, ...,
         4.11130343e-05, -3.12913383e-02,  1.56609092e-01]])

In [39]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [46]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_project_ids = df_final['id'].iloc[project_indices].tolist()
    result_dict = {}
    for i, project_id in enumerate(recommended_project_ids):
        result_dict[i + 1] = project_id

    return result_dict

In [47]:
get_recommendations("dog")

{1: 3,
 2: 45,
 3: 69,
 4: 20,
 5: 6,
 6: 67,
 7: 33,
 8: 27,
 9: 10,
 10: 24,
 11: 68,
 12: 36,
 13: 29,
 14: 66,
 15: 56,
 16: 62,
 17: 54,
 18: 50,
 19: 51}

Hora de enviar los resultados de la similitud de cosenos entre vectores a la base de datos

In [50]:
send_recomendations_url = "http://localhost:3000/recommendations/recommend"

payloadRec = get_recommendations("dog")

response_recommend = requests.post(send_recomendations_url, headers=headers_projects, json=payloadRec)
recommendation_data = response_recommend.json()

ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /recommendations/recommend (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000240224550B8>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión',))