In [1]:
%pip install pandas
%pip install requests
%pip install numpy
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


     -------------------------------------- 300.9/300.9 MB 4.5 MB/s eta 0:00:00
     -------------------------------------- 130.2/130.2 kB 8.0 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB 3.0 MB/s eta 0:00:00
     ---------------------------------------- 2.7/2.7 MB 10.0 MB/s eta 0:00:00
     --------------------------------------- 24.4/24.4 MB 10.2 MB/s eta 0:00:00
     -------------------------------------- 938.7/938.7 kB 9.9 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB ? eta 0:00:00
     -------------------------------------- 413.4/413.4 kB 8.6 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 10.5 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 11.2 MB/s eta 0:00:00
     ---------------------------------------- 5.5/5.5 MB 11.1 MB/s eta 0:00:00
     ------------------------------------- 442.0/442.0 kB 13.5 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [3]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()


print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow dog dog a ab a aB ab abc abc poll abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a abc a abc a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a abc abc ab abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a

In [4]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [5]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [6]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

    Palabra
0       dog
1      aaaa
2    holaaa
3      siii
4      siii
..      ...
567      ab
568       a
569      ab
570       a
571     wow

[572 rows x 1 columns]
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
15     cat
16     cat
17     cat
18     cat
19     cat
20     cat
21     cat
22     ggg
23     ggg
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7    8                                     sssss 

In [7]:
df3.head(15)

id                 name         description  creatorId  \
0    1                  cat                blue          2   
1    2                  dog                 red          2   
2    3                doggf                 red         56   
3    4                catff                blue         56   
4    5                lemur                grey         56   
5    6                  ppo                 ppo         56   
6    7                  ddd                 ddd         56   
7    8                sssss                 sss         56   
8    9                  sss                 sss         56   
9   10                  ggg                 ggg         56   
10  15     modified bruuhhh  modified testinggg         56   
11  17                    s                   s         56   
12  20        proyecto pepe    que tal soy sech         56   
13  21     allprojects test                sape         56   
14  24  getallprojects test                sest         56   

                   createdAt                 updatedAt  
0   2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1   2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2   2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3   2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4   2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5   2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6   2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7   2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8   2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9   2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [8]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(572, 1)
(24, 1)
(53, 6)


In [9]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(53, 6)


In [10]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId
0     dog     dog   1    cat        blue          2
1    aaaa     cat   2    dog         red          2
2  holaaa     dog   3  doggf         red         56
3    siii     cat   4  catff        blue         56
4    siii     cat   5  lemur        grey         56
5     dog   doggf   6    ppo         ppo         56
6     dog     cat   7    ddd         ddd         56
7     dog     cat   8  sssss         sss         56
8     cat     cat   9    sss         sss         56
9     wow     cat  10    ggg         ggg         56

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [11]:
%pip install scikit-learn

     ---------------------------------------- 9.2/9.2 MB 10.5 MB/s eta 0:00:00
     ---------------------------------------- 44.1/44.1 MB 8.4 MB/s eta 0:00:00
     -------------------------------------- 302.2/302.2 kB 9.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
tfidf = TfidfVectorizer(max_features=5000)

In [14]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [15]:
print(type(vectorized_data))

<class 'scipy.sparse._csr.csr_matrix'>


In [16]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [17]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    40   41   42   43   44   45  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 46 columns]

In [18]:
vectorized_dataframe.shape

(53, 46)

In [19]:
from sklearn.decomposition import TruncatedSVD

In [20]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [21]:
reduced_data.shape

(53, 14)

In [22]:
reduced_data

array([[ 1.71392298e-06, -2.99808247e-01,  1.21182663e-01,
         9.42808144e-01,  8.03260131e-02,  3.70215125e-04,
         2.11133195e-16,  7.54769848e-17,  6.06971838e-17,
        -2.14557684e-17,  1.89996706e-16,  1.74243892e-16,
        -8.45587618e-17, -4.41422826e-17],
       [ 1.26774312e-06, -6.22343659e-01,  6.75039515e-01,
        -3.06083389e-01,  2.51509857e-01, -1.53264991e-04,
         1.10442174e-16,  1.79044117e-16, -7.52889971e-17,
        -7.29818371e-17, -1.06065703e-16, -5.63246380e-17,
         3.13765396e-17,  4.26098342e-17],
       [ 1.26774312e-06, -6.22343659e-01,  6.75039515e-01,
        -3.06083389e-01,  2.51509857e-01, -1.53264991e-04,
         1.10442174e-16,  1.79044117e-16, -7.52889971e-17,
        -7.29818371e-17, -1.06065703e-16, -5.63246380e-17,
         3.13765396e-17,  4.26098342e-17],
       [ 1.71392298e-06, -2.99808247e-01,  1.21182663e-01,
         9.42808144e-01,  8.03260131e-02,  3.70215125e-04,
         2.11133195e-16,  7.54769848e-17,  6.

In [23]:
svd.explained_variance_ratio_.cumsum()

array([0.08832753, 0.13716002, 0.18560822, 0.23402386, 0.27703063,
       0.31890212, 0.3433176 , 0.36746519, 0.39198723, 0.41660828,
       0.44119597, 0.46331571, 0.48748799, 0.51068404])

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
similarity = cosine_similarity(reduced_data)

In [26]:
similarity

array([[ 1.00000000e+00,  1.16641975e-05,  1.16641975e-05, ...,
         4.78160747e-04,  1.32234914e-04,  1.28989132e-03],
       [ 1.16641975e-05,  1.00000000e+00,  1.00000000e+00, ...,
         5.44160525e-03,  6.93507855e-04, -5.05117097e-04],
       [ 1.16641975e-05,  1.00000000e+00,  1.00000000e+00, ...,
         5.44160525e-03,  6.93507855e-04, -5.05117097e-04],
       ...,
       [ 4.78160747e-04,  5.44160525e-03,  5.44160525e-03, ...,
         1.00000000e+00,  8.29183495e-02,  7.22766829e-02],
       [ 1.32234914e-04,  6.93507855e-04,  6.93507855e-04, ...,
         8.29183495e-02,  1.00000000e+00, -3.66946967e-01],
       [ 1.28989132e-03, -5.05117097e-04, -5.05117097e-04, ...,
         7.22766829e-02, -3.66946967e-01,  1.00000000e+00]])

In [27]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 9.99909825e-01,  1.16632881e-05,  1.16632881e-05, ...,
         1.84659519e-04,  8.46306284e-05,  7.95303909e-04],
       [ 1.16632881e-05,  9.99934250e-01,  9.99934250e-01, ...,
         2.10150350e-03,  4.43851935e-04, -3.11442136e-04],
       [ 1.16632881e-05,  9.99934250e-01,  9.99934250e-01, ...,
         2.10150350e-03,  4.43851935e-04, -3.11442136e-04],
       ...,
       [ 1.84659519e-04,  2.10150350e-03,  2.10150350e-03, ...,
         1.49153938e-01,  2.04959957e-02,  1.72113585e-02],
       [ 8.46306284e-05,  4.43851935e-04,  4.43851935e-04, ...,
         2.04959957e-02,  4.09639684e-01, -1.44811780e-01],
       [ 7.95303909e-04, -3.11442136e-04, -3.11442136e-04, ...,
         1.72113585e-02, -1.44811780e-01,  3.80188657e-01]])

In [28]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [29]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_project_ids = df_final['id'].iloc[project_indices].tolist()
    result_dict = {}
    for i, project_id in enumerate(recommended_project_ids):
        result_dict[i + 1] = project_id

    return result_dict

In [30]:
get_recommendations("dog")

{1: 3,
 2: 35,
 3: 25,
 4: 24,
 5: 67,
 6: 49,
 7: 15,
 8: 54,
 9: 45,
 10: 65,
 11: 62,
 12: 68,
 13: 10,
 14: 31,
 15: 6,
 16: 66,
 17: 43,
 18: 44,
 19: 60}

Hora de enviar los resultados de la similitud de cosenos entre vectores a la base de datos

In [31]:
%pip install flask

     ---------------------------------------- 99.7/99.7 kB 5.6 MB/s eta 0:00:00
     ---------------------------------------- 97.9/97.9 kB 5.5 MB/s eta 0:00:00
  Attempting uninstall: click
    Found existing installation: click 7.1.2
    Uninstalling click-7.1.2:
      Successfully uninstalled click-7.1.2
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
p 1.4.0 requires click<8.0.0,>=7.1.2, but you have click 8.1.7 which is incompatible.

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/mi_ruta', methods=['GET'])
def obtener_resultados():
    # Llama a tu función y obtén los resultados
    resultados = get_recommendations()

    # Convierte los resultados a un formato adecuado (por ejemplo, JSON)
    resultados_json = jsonify(resultados)

    # Puedes retornar los resultados como respuesta
    return resultados_json

if __name__ == '__main__':
    app.run(debug=True)