#Acordate de agarrar con el github desktop el brunch de BACK y ponerlo en la PC de casa para despues, correr el server en el localhost:3000 y poder utilizar este codigo

In [7]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [8]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()

print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow 
dog cat dog cat cat doggf cat cat cat cat cat cat cat cat uuuuuu
[{'id': 1, 'name': 'cat', 'description': 'blue', 'creatorId': 2, 'createdAt': '2023-10-30T13:39:26.619Z', 'updatedAt': '2023-10-30T13:39:26.619Z'}, {'id': 2, 'name': 'dog', 'description': 'red', 'creatorId': 2, 'createdAt': '2023-10-30T13:39:46.698Z', 'updatedAt': '2023-10-30T13:39:46.698Z'}, {'id': 3, 'name': 'doggf', 'description': 'red', 'creatorId': 56, 'createdAt': '2023-11-01T21:16:53.796Z', 'updatedAt': '2023-11-03T01:05:23.711Z'}, {'id': 4, 'name': 'catff', 'description': 'blue', 'creatorId': 56, 'createdAt': '2023-11-01T21:17:02.209Z', 'updatedAt': '2023-11-03T01:06:51.653Z'}, {'id': 5, 'name': 'lemur', 'description': 'grey', 'creatorId': 56, 'createdAt': '2023-11-01T21:17:15.554Z', 'updatedAt': '2023-11-01T21:17:15.554Z'}, {'id': 6, 'name': 'ppo', 'description': 'ppo', 'creatorId': 56, 'createdAt': '2023-11-01T22:23:22.617Z', 'updatedAt': '2023-11-01T22:23:22.617Z'}

In [9]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [10]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [11]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

  Palabra
0     dog
1    aaaa
2  holaaa
3    siii
4    siii
5     dog
6     dog
7     dog
8     cat
9     wow
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7    8                                     sssss   
8    9                                       sss   
9   10                                       ggg   
10  15                          modified bruuhhh  

In [119]:
df3.head(15)

id                 name         description  creatorId  \
0    1                  cat                blue          2   
1    2                  dog                 red          2   
2    3                doggf                 red         56   
3    4                catff                blue         56   
4    5                lemur                grey         56   
5    6                  ppo                 ppo         56   
6    7                  ddd                 ddd         56   
7    8                sssss                 sss         56   
8    9                  sss                 sss         56   
9   10                  ggg                 ggg         56   
10  15     modified bruuhhh  modified testinggg         56   
11  17                    s                   s         56   
12  20        proyecto pepe    que tal soy sech         56   
13  21     allprojects test                sape         56   
14  24  getallprojects test                sest         56   

                   createdAt                 updatedAt  
0   2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1   2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2   2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3   2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4   2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5   2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6   2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7   2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8   2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9   2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [118]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(10, 1)
(15, 1)
(45, 6)


In [203]:
# Concatenar df1 y df2 a lo largo de las columnas
df_concatenated = pd.concat([df1, df2], axis=1)

# Unir df_concatenated con df3 basado en el índice (puedes ajustar el método de unión según tus necesidades)
df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

# Si df3 tiene una columna adicional que no necesitas para la unión, puedes eliminarla
df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

# Imprimir la forma del DataFrame final
print(df_final.shape)

(15, 6)


In [204]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId
0     dog     dog   1    cat        blue          2
1    aaaa     cat   2    dog         red          2
2  holaaa     dog   3  doggf         red         56
3    siii     cat   4  catff        blue         56
4    siii     cat   5  lemur        grey         56
5     dog   doggf   6    ppo         ppo         56
6     dog     cat   7    ddd         ddd         56
7     dog     cat   8  sssss         sss         56
8     cat     cat   9    sss         sss         56
9     wow     cat  10    ggg         ggg         56

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
tfidf = TfidfVectorizer(max_features=5000)

In [161]:
vectorized_data = tfidf.transform(df_final["description"])

In [162]:
print(type(vectorized_data))

<class 'scipy.sparse.csr.csr_matrix'>


In [164]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [165]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   28   29   30   31  \
0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0  0.0   

    32   33   34   35   36   37  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 38 columns]

In [166]:
vectorized_dataframe.shape

(15, 38)

In [167]:
from sklearn.decomposition import TruncatedSVD

In [187]:
svd = TruncatedSVD(n_components=37)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [188]:
reduced_data.shape

(15, 15)

In [189]:
reduced_data

array([[-1.02455848e-16,  1.00000000e+00, -1.75092267e-16,
         2.53578274e-19,  8.62008191e-18, -1.59345605e-18,
         5.98362615e-18,  1.54561048e-18,  3.63310708e-18,
         4.48459446e-18, -1.22027285e-17, -1.38786739e-31,
         3.44771600e-32,  3.22503072e-33, -1.55462301e-32],
       [-4.41355296e-01,  8.17649526e-17,  8.97332437e-01,
         1.44187464e-16, -2.47916304e-17, -2.55436498e-16,
         9.16260978e-17, -1.28103571e-19, -1.10557941e-16,
         4.35022829e-16,  3.83711770e-16, -7.88308073e-17,
        -1.27123655e-16, -4.25222205e-19,  3.54450260e-18],
       [-4.41355296e-01,  8.17649526e-17,  8.97332437e-01,
         1.44187464e-16, -2.47916304e-17, -2.55436498e-16,
         9.16260978e-17, -1.28103571e-19, -1.10557941e-16,
         4.35022829e-16,  3.83711770e-16, -7.88308073e-17,
        -1.27123655e-16, -4.25222205e-19,  3.54450260e-18],
       [-1.02455848e-16,  1.00000000e+00, -1.75092267e-16,
         2.53578274e-19,  8.62008191e-18, -1.59345605

In [190]:
svd.explained_variance_ratio_.cumsum()

array([0.15351758, 0.29035968, 0.41052632, 0.48671406, 0.55990278,
       0.6367901 , 0.7097945 , 0.78008229, 0.85229468, 0.92946841,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [191]:
from sklearn.metrics.pairwise import cosine_similarity

In [192]:
similarity = cosine_similarity(reduced_data)

In [193]:
similarity

array([[ 1.00000000e+00, -3.01315869e-17, -3.01315869e-17,
         1.00000000e+00, -4.90038954e-18,  2.22913272e-17,
         2.65821180e-17, -9.44726651e-17, -9.44726651e-17,
        -3.27241694e-18,  1.64255540e-17,  0.00000000e+00,
         2.77262967e-17, -1.01554473e-17,  1.33599127e-17],
       [-3.01315869e-17,  1.00000000e+00,  1.00000000e+00,
        -3.01315869e-17,  2.11214852e-17,  1.38569429e-16,
        -1.15563794e-16, -1.16504771e-16, -1.16504771e-16,
         1.43208398e-17, -2.61808849e-17,  0.00000000e+00,
        -2.53042152e-16, -7.51000666e-17,  1.01430451e-16],
       [-3.01315869e-17,  1.00000000e+00,  1.00000000e+00,
        -3.01315869e-17,  2.11214852e-17,  1.38569429e-16,
        -1.15563794e-16, -1.16504771e-16, -1.16504771e-16,
         1.43208398e-17, -2.61808849e-17,  0.00000000e+00,
        -2.53042152e-16, -7.51000666e-17,  1.01430451e-16],
       [ 1.00000000e+00, -3.01315869e-17, -3.01315869e-17,
         1.00000000e+00, -4.90038954e-18,  2.22913272

In [207]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 1.00000000e+00, -3.01315869e-17, -3.01315869e-17,
         1.00000000e+00, -4.90038954e-18,  2.22913272e-17,
         2.65821180e-17, -9.44726651e-17, -9.44726651e-17,
        -3.27241694e-18,  1.64255540e-17,  0.00000000e+00,
         2.77262967e-17, -1.01554473e-17,  1.33599127e-17],
       [-3.01315869e-17,  1.00000000e+00,  1.00000000e+00,
        -3.01315869e-17,  2.11214852e-17,  1.38569429e-16,
        -1.15563794e-16, -8.55737711e-17, -8.55737711e-17,
         1.43208398e-17, -2.61808849e-17,  0.00000000e+00,
        -2.53042152e-16, -7.51000666e-17,  1.01430451e-16],
       [-3.01315869e-17,  1.00000000e+00,  1.00000000e+00,
        -3.01315869e-17,  2.11214852e-17,  1.38569429e-16,
        -1.15563794e-16, -8.55737711e-17, -8.55737711e-17,
         1.43208398e-17, -2.61808849e-17,  0.00000000e+00,
        -2.53042152e-16, -7.51000666e-17,  1.01430451e-16],
       [ 1.00000000e+00, -3.01315869e-17, -3.01315869e-17,
         1.00000000e+00, -4.90038954e-18,  2.22913272

In [208]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [224]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    movie_indices = [i[0] for i in sim_scores]

    recommended_projects = df_final['name'].iloc[movie_indices].tolist()
    result_dict = {}
    for i, movie in enumerate(recommended_projects):
        result_dict[i + 1] = movie

    return result_dict

In [225]:
get_recommendations("dog")

{1: 'doggf',
 2: 'ppo',
 3: 'getallprojects test',
 4: 'lemur',
 5: 'ggg',
 6: 's',
 7: 'modified bruuhhh',
 8: 'cat',
 9: 'catff',
 10: 'allprojects test',
 11: 'sssss',
 12: 'sss',
 13: 'ddd',
 14: 'proyecto pepe'}