In [88]:
%pip install pandas
%pip install requests
%pip install numpy
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [89]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [90]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()


print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow dog dog a ab a aB ab abc abc poll abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a abc a abc a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a abc abc ab abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a

In [91]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [92]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [93]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

        Palabra
0           dog
1          aaaa
2        holaaa
3          siii
4          siii
..          ...
573          al
574       allpr
575          al
576        sape
577  adtgyfuyui

[578 rows x 1 columns]
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
15     cat
16     cat
17     cat
18     cat
19     cat
20     cat
21     cat
22     ggg
23     ggg
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7

In [94]:
df3.head(15)

id                 name         description  creatorId  \
0    1                  cat                blue          2   
1    2                  dog                 red          2   
2    3                doggf                 red         56   
3    4                catff                blue         56   
4    5                lemur                grey         56   
5    6                  ppo                 ppo         56   
6    7                  ddd                 ddd         56   
7    8                sssss                 sss         56   
8    9                  sss                 sss         56   
9   10                  ggg                 ggg         56   
10  15     modified bruuhhh  modified testinggg         56   
11  17                    s                   s         56   
12  20        proyecto pepe    que tal soy sech         56   
13  21     allprojects test                sape         56   
14  24  getallprojects test                sest         56   

                   createdAt                 updatedAt  
0   2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1   2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2   2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3   2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4   2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5   2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6   2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7   2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8   2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9   2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [95]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(578, 1)
(24, 1)
(54, 6)


In [96]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(54, 6)


In [97]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId
0     dog     dog   1    cat        blue          2
1    aaaa     cat   2    dog         red          2
2  holaaa     dog   3  doggf         red         56
3    siii     cat   4  catff        blue         56
4    siii     cat   5  lemur        grey         56
5     dog   doggf   6    ppo         ppo         56
6     dog     cat   7    ddd         ddd         56
7     dog     cat   8  sssss         sss         56
8     cat     cat   9    sss         sss         56
9     wow     cat  10    ggg         ggg         56

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [98]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [99]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [100]:
tfidf = TfidfVectorizer(max_features=5000)

In [101]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [102]:
print(type(vectorized_data))

<class 'scipy.sparse._csr.csr_matrix'>


In [103]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [104]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    40   41   42   43   44   45  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 46 columns]

In [105]:
vectorized_dataframe.shape

(54, 46)

In [106]:
from sklearn.decomposition import TruncatedSVD

In [107]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [108]:
reduced_data.shape

(54, 14)

In [109]:
reduced_data

array([[ 8.21970077e-07,  5.73471267e-04, -1.58891460e-01,
         5.30295412e-01, -4.00126270e-01,  7.30293624e-01,
         2.73905028e-05, -4.25843908e-17, -8.32787450e-17,
         4.10807097e-16, -1.45287764e-16, -3.95469505e-17,
        -3.34310551e-16,  3.40834864e-17],
       [ 1.58873649e-08,  2.04959884e-04,  7.31513049e-01,
         6.08932218e-01,  2.77255956e-01, -1.31081996e-01,
        -8.00833125e-05,  5.58339899e-17,  1.75095969e-16,
        -3.81145887e-17,  1.79355816e-16, -8.02261290e-17,
         6.54342013e-18,  3.69395491e-17],
       [ 1.58873649e-08,  2.04959884e-04,  7.31513049e-01,
         6.08932218e-01,  2.77255956e-01, -1.31081996e-01,
        -8.00833125e-05,  5.58339899e-17,  1.75095969e-16,
        -3.81145887e-17,  1.79355816e-16, -8.02261290e-17,
         6.54342013e-18,  3.69395491e-17],
       [ 8.21970077e-07,  5.73471267e-04, -1.58891460e-01,
         5.30295412e-01, -4.00126270e-01,  7.30293624e-01,
         2.73905028e-05, -4.25843908e-17, -8.

In [110]:
svd.explained_variance_ratio_.cumsum()

array([0.09040882, 0.14312244, 0.19099073, 0.23313048, 0.27995358,
       0.32781082, 0.35211201, 0.37615494, 0.39904245, 0.42304613,
       0.44708072, 0.47109914, 0.49503966, 0.518674  ])

In [111]:
from sklearn.metrics.pairwise import cosine_similarity

In [112]:
similarity = cosine_similarity(reduced_data)

In [113]:
similarity

array([[ 1.00000000e+00,  1.71638742e-05,  1.71638742e-05, ...,
         3.09233509e-03,  1.07815715e-03, -6.25818692e-04],
       [ 1.71638742e-05,  1.00000000e+00,  1.00000000e+00, ...,
        -4.92968661e-04,  5.87670845e-04,  8.89609041e-04],
       [ 1.71638742e-05,  1.00000000e+00,  1.00000000e+00, ...,
        -4.92968661e-04,  5.87670845e-04,  8.89609041e-04],
       ...,
       [ 3.09233509e-03, -4.92968661e-04, -4.92968661e-04, ...,
         1.00000000e+00,  2.24811445e-01,  5.42115976e-02],
       [ 1.07815715e-03,  5.87670845e-04,  5.87670845e-04, ...,
         2.24811445e-01,  1.00000000e+00,  6.83036752e-02],
       [-6.25818692e-04,  8.89609041e-04,  8.89609041e-04, ...,
         5.42115976e-02,  6.83036752e-02,  1.00000000e+00]])

In [114]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 9.99889858e-01,  1.71626131e-05,  1.71626131e-05, ...,
         1.35478518e-03,  6.38613526e-04, -5.92365131e-04],
       [ 1.71626131e-05,  9.99963191e-01,  9.99963191e-01, ...,
        -2.15982778e-04,  3.48101677e-04,  8.42085267e-04],
       [ 1.71626131e-05,  9.99963191e-01,  9.99963191e-01, ...,
        -2.15982778e-04,  3.48101677e-04,  8.42085267e-04],
       ...,
       [ 1.35478518e-03, -2.15982778e-04, -2.15982778e-04, ...,
         1.91962152e-01,  5.83453415e-02,  2.24835500e-02],
       [ 6.38613526e-04,  3.48101677e-04,  3.48101677e-04, ...,
         5.83453415e-02,  3.50881061e-01,  3.82991301e-02],
       [-5.92365131e-04,  8.42085267e-04,  8.42085267e-04, ...,
         2.24835500e-02,  3.82991301e-02,  8.96044850e-01]])

In [115]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [129]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_projects = [{"projectId": int(df_final['id'].iloc[i])} for i in project_indices]
    """recommended_project_ids = df_final['id'].iloc[project_indices].tolist()
    result_projects = [recommended_project_ids] """
    
    return recommended_projects

In [130]:
get_recommendations("dog")

[{'projectId': 3},
 {'projectId': 6},
 {'projectId': 10},
 {'projectId': 27},
 {'projectId': 24},
 {'projectId': 5},
 {'projectId': 50},
 {'projectId': 51},
 {'projectId': 55},
 {'projectId': 32},
 {'projectId': 62},
 {'projectId': 53},
 {'projectId': 56},
 {'projectId': 70},
 {'projectId': 47},
 {'projectId': 66},
 {'projectId': 69},
 {'projectId': 7},
 {'projectId': 35}]

In [131]:
print(type(get_recommendations("dog")[0]))

<class 'dict'>


Hora de enviar los resultados de la similitud de cosenos entre vectores a la base de datos

In [133]:
import json
import time

# Retry function with exponential backoff
def retry_request(url, data, headers, retries=3, delay=1):
    for i in range(retries):
        try:
            response = requests.post(url, data=json.dumps(data), headers=headers)
            return response
        except requests.exceptions.ConnectionError:
            print(f"Connection error. Retrying in {delay} seconds...")
            time.sleep(delay)
            delay *= 2
    return None

url = "http://localhost:3000/recommendations/recommend"

res = get_recommendations("cat")

datos_json = {
    "id": 56,
    "projectsWithAffinities": res
} 

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

print("Hola")
respuesta = retry_request(url, datos_json, encabezado)

print("Hola")
if respuesta is not None and respuesta.status_code == 200:
    print('Solicitud exitosa. Respuesta del servidor:')
    print(respuesta.json())
else:
    print(f'Error en la solicitud. Código de estado: {respuesta.status_code}')
    print(respuesta.text if respuesta else "No response")

""" print(datos_json)

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

print("Hola")
respuesta = requests.post(url, data=json.dumps(datos_json), headers=encabezado)


print("Hola")
if respuesta.status_code == 200:
    print('Solicitud exitosa. Respuesta del servidor:')
    print(respuesta.json())
else:
    print(f'Error en la solicitud. Código de estado: {respuesta.status_code}')
    print(respuesta.text) """

Hola
Connection error. Retrying in 1 seconds...
Connection error. Retrying in 2 seconds...
Connection error. Retrying in 4 seconds...
Hola
Error en la solicitud. Código de estado: None
No response


' print(datos_json)\n\nencabezado = {\n    "Authorization": "Bearer",\n    "Content-Type": "application/json",\n    "x-api-key": "REYDEREDES"\n}\n\nprint("Hola")\nrespuesta = requests.post(url, data=json.dumps(datos_json), headers=encabezado)\n\n\nprint("Hola")\nif respuesta.status_code == 200:\n    print(\'Solicitud exitosa. Respuesta del servidor:\')\n    print(respuesta.json())\nelse:\n    print(f\'Error en la solicitud. Código de estado: {respuesta.status_code}\')\n    print(respuesta.text) '