In [4]:
%pip install pandas
%pip install requests
%pip install numpy
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [54]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()


print(search_history_data)
print(visit_history_data)
print(all_projects_data)


dog aaaa holaaa siii siii dog dog dog cat wow dog dog a ab a aB ab abc abc poll abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a abc a abc a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a abc abc ab abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc a

In [7]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [8]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [9]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

        Palabra
0           dog
1          aaaa
2        holaaa
3          siii
4          siii
..          ...
573          al
574       allpr
575          al
576        sape
577  adtgyfuyui

[578 rows x 1 columns]
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
15     cat
16     cat
17     cat
18     cat
19     cat
20     cat
21     cat
22     ggg
23     ggg
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7

In [10]:
df3.head(15)

id                 name         description  creatorId  \
0    1                  cat                blue          2   
1    2                  dog                 red          2   
2    3                doggf                 red         56   
3    4                catff                blue         56   
4    5                lemur                grey         56   
5    6                  ppo                 ppo         56   
6    7                  ddd                 ddd         56   
7    8                sssss                 sss         56   
8    9                  sss                 sss         56   
9   10                  ggg                 ggg         56   
10  15     modified bruuhhh  modified testinggg         56   
11  17                    s                   s         56   
12  20        proyecto pepe    que tal soy sech         56   
13  21     allprojects test                sape         56   
14  24  getallprojects test                sest         56   

                   createdAt                 updatedAt  
0   2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1   2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2   2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3   2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4   2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5   2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6   2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7   2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8   2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9   2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [11]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(578, 1)
(24, 1)
(53, 6)


In [12]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(53, 6)


In [13]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId
0     dog     dog   1    cat        blue          2
1    aaaa     cat   2    dog         red          2
2  holaaa     dog   3  doggf         red         56
3    siii     cat   4  catff        blue         56
4    siii     cat   5  lemur        grey         56
5     dog   doggf   6    ppo         ppo         56
6     dog     cat   7    ddd         ddd         56
7     dog     cat   8  sssss         sss         56
8     cat     cat   9    sss         sss         56
9     wow     cat  10    ggg         ggg         56

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [14]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [16]:
tfidf = TfidfVectorizer(max_features=5000)

In [17]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [18]:
print(type(vectorized_data))

<class 'scipy.sparse._csr.csr_matrix'>


In [19]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [20]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9   ...   36   37   38   39  \
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    40   41   42   43   44   45  
0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 46 columns]

In [21]:
vectorized_dataframe.shape

(53, 46)

In [22]:
from sklearn.decomposition import TruncatedSVD

In [23]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [24]:
reduced_data.shape

(53, 14)

In [25]:
reduced_data

array([[ 2.30025370e-06, -4.58328449e-01, -8.76202017e-02,
         1.05066846e-02,  8.84160814e-01, -1.53778036e-04,
         4.16623358e-16, -2.86778404e-16,  2.12256871e-16,
        -1.58418175e-16,  7.32929271e-17, -3.23186085e-16,
         7.11921391e-17,  1.46136009e-16],
       [ 4.36776275e-06,  4.01349184e-01, -6.43124875e-01,
         6.37537447e-01,  1.36686335e-01, -2.77250073e-04,
         9.37233641e-17, -1.29556820e-16, -8.38823835e-18,
        -1.24633524e-16, -2.34695266e-16, -1.32165679e-16,
         1.74092547e-16,  1.37916557e-16],
       [ 4.36776275e-06,  4.01349184e-01, -6.43124875e-01,
         6.37537447e-01,  1.36686335e-01, -2.77250073e-04,
         9.37233641e-17, -1.29556820e-16, -8.38823835e-18,
        -1.24633524e-16, -2.34695266e-16, -1.32165679e-16,
         1.74092547e-16,  1.37916557e-16],
       [ 2.30025370e-06, -4.58328449e-01, -8.76202017e-02,
         1.05066846e-02,  8.84160814e-01, -1.53778036e-04,
         4.16623358e-16, -2.86778404e-16,  2.

In [26]:
svd.explained_variance_ratio_.cumsum()

array([0.08832765, 0.13598184, 0.18508875, 0.23271736, 0.27702639,
       0.31890702, 0.34352264, 0.36763337, 0.39076621, 0.41493654,
       0.43945335, 0.4638371 , 0.48838266, 0.5129178 ])

In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
similarity = cosine_similarity(reduced_data)

In [29]:
similarity

array([[ 1.00000000e+00, -4.78827543e-05, -4.78827543e-05, ...,
        -2.83411705e-04, -1.23817515e-02, -2.76303506e-03],
       [-4.78827543e-05,  1.00000000e+00,  1.00000000e+00, ...,
         3.04812288e-03,  2.26114905e-03,  3.26636795e-03],
       [-4.78827543e-05,  1.00000000e+00,  1.00000000e+00, ...,
         3.04812288e-03,  2.26114905e-03,  3.26636795e-03],
       ...,
       [-2.83411705e-04,  3.04812288e-03,  3.04812288e-03, ...,
         1.00000000e+00,  3.67087153e-01,  6.32626623e-02],
       [-1.23817515e-02,  2.26114905e-03,  2.26114905e-03, ...,
         3.67087153e-01,  1.00000000e+00, -5.14504817e-01],
       [-2.76303506e-03,  3.26636795e-03,  3.26636795e-03, ...,
         6.32626623e-02, -5.14504817e-01,  1.00000000e+00]])

In [30]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 9.99593025e-01, -4.78688926e-05, -4.78688926e-05, ...,
        -1.96267090e-04, -5.08979513e-03, -1.83145650e-03],
       [-4.78688926e-05,  9.99828000e-01,  9.99828000e-01, ...,
         2.11112141e-03,  9.29604993e-04,  2.16534129e-03],
       [-4.78688926e-05,  9.99828000e-01,  9.99828000e-01, ...,
         2.11112141e-03,  9.29604993e-04,  2.16534129e-03],
       ...,
       [-1.96267090e-04,  2.11112141e-03,  2.11112141e-03, ...,
         4.79773418e-01,  1.04542742e-01,  2.90512056e-02],
       [-5.08979513e-03,  9.29604993e-04,  9.29604993e-04, ...,
         1.04542742e-01,  1.69049239e-01, -1.40247348e-01],
       [-1.83145650e-03,  2.16534129e-03,  2.16534129e-03, ...,
         2.90512056e-02, -1.40247348e-01,  4.39538789e-01]])

In [31]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [80]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_projects = [{"projectId": int(df_final['id'].iloc[i])} for i in project_indices]
    
    return recommended_projects

In [81]:
get_recommendations("dog")

[{'projectId': 3},
 {'projectId': 65},
 {'projectId': 6},
 {'projectId': 5},
 {'projectId': 52},
 {'projectId': 20},
 {'projectId': 53},
 {'projectId': 66},
 {'projectId': 69},
 {'projectId': 32},
 {'projectId': 67},
 {'projectId': 21},
 {'projectId': 27},
 {'projectId': 10},
 {'projectId': 15},
 {'projectId': 33},
 {'projectId': 7},
 {'projectId': 68},
 {'projectId': 49}]

Hora de enviar los resultados de la similitud de cosenos entre vectores a la base de datos

In [37]:
%pip install fastapi
%pip install "uvicorn[standard]"

     ---------------------------------------- 92.9/92.9 kB 2.7 MB/s eta 0:00:00
     ---------------------------------------- 80.9/80.9 kB 4.7 MB/s eta 0:00:00
     -------------------------------------- 381.9/381.9 kB 7.9 MB/s eta 0:00:00
     ---------------------------------------- 67.0/67.0 kB ? eta 0:00:00
     ---------------------------------------- 1.9/1.9 MB 10.0 MB/s eta 0:00:00
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.6.3
    Uninstalling typing_extensions-4.6.3:
      Successfully uninstalled typing_extensions-4.6.3
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


     ---------------------------------------- 59.7/59.7 kB 1.1 MB/s eta 0:00:00
     ---------------------------------------- 58.3/58.3 kB 1.5 MB/s eta 0:00:00
     ---------------------------------------- 55.4/55.4 kB 2.8 MB/s eta 0:00:00
     -------------------------------------- 144.7/144.7 kB 8.4 MB/s eta 0:00:00
     -------------------------------------- 280.1/280.1 kB 8.7 MB/s eta 0:00:00
     -------------------------------------- 125.0/125.0 kB 7.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [83]:
import json

url = "http://localhost:3000/recommendations/recommend"

datos_json = {
    "id": 56,
    "projectsWithAffinities": get_recommendations("cat")  
} 

print(datos_json)

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

print("Hola")
respuesta = requests.post(url, data=datos_json, headers=encabezado)


print("Hola")
if respuesta.status_code == 200:
    print('Solicitud exitosa. Respuesta del servidor:')
    print(respuesta.json())
else:
    print(f'Error en la solicitud. Código de estado: {respuesta.status_code}')
    print(respuesta.text)

{'id': 56, 'projectsWithAffinities': [{'projectId': 4}, {'projectId': 10}, {'projectId': 21}, {'projectId': 54}, {'projectId': 65}, {'projectId': 20}, {'projectId': 6}, {'projectId': 25}, {'projectId': 5}, {'projectId': 15}, {'projectId': 53}, {'projectId': 47}, {'projectId': 36}, {'projectId': 49}, {'projectId': 29}, {'projectId': 43}, {'projectId': 44}, {'projectId': 60}, {'projectId': 17}]}
Hola
Hola
Error en la solicitud. Código de estado: 400
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token i in JSON at position 0<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at createStrictSyntaxError (C:\Users\47295973\Documents\GitHub\startapp-final\node_modules\body-parser\lib\types\json.js:160:10)<br> &nbsp; &nbsp;at parse (C:\Users\47295973\Documents\GitHub\startapp-final\node_modules\body-parser\lib\types\json.js:83:15)<br> &nbsp; &nbsp;at C:\Users\47295973\Documents\GitHub\startapp-fi