#Acordate de agarrar con el github desktop el brunch de BACK y ponerlo en la PC de casa para despues, correr el server en el localhost:3000 y poder utilizar este codigo

In [2]:
import pandas as pd
import requests
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [3]:
search_history_url = "http://localhost:3000/userData/searchHistory"
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}
payload = {
    "userId": "2"
}
response_search_history = requests.get(search_history_url, headers=headers, json=payload)
search_history_data = response_search_history.json()


visit_history_url = "http://localhost:3000/userData/visitHistory"
response_visit_history = requests.get(visit_history_url, headers=headers, json=payload)
visit_history_data = response_visit_history.json()


get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()

print(search_history_data)
print(visit_history_data)
print(all_projects_data)


ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /userData/searchHistory (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CC415682B0>: Failed to establish a new connection: [WinError 10061] No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión',))

In [ ]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'statusId': 1,
 'maxMembers': 5,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z'}

In [ ]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'Palabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [ ]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

  Palabra
0     dog
1    aaaa
2  holaaa
3    siii
4    siii
5     dog
6     dog
7     dog
8     cat
9     wow
--------------------------------------------

   Palabra
0      dog
1      cat
2      dog
3      cat
4      cat
5    doggf
6      cat
7      cat
8      cat
9      cat
10     cat
11     cat
12     cat
13     cat
14  uuuuuu
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7    8                                     sssss   
8    9                                       sss   
9   10                                       ggg   
10  15                          modified bruuhhh  

In [ ]:
df3.head(15)

id                 name         description  creatorId  statusId  \
0    1                  cat                blue          2         1   
1    2                  dog                 red          2         1   
2    3                doggf                 red         56         1   
3    4                catff                blue         56         1   
4    5                lemur                grey         56         1   
5    6                  ppo                 ppo         56         1   
6    7                  ddd                 ddd         56         1   
7    8                sssss                 sss         56         1   
8    9                  sss                 sss         56         1   
9   10                  ggg                 ggg         56         1   
10  15     modified bruuhhh  modified testinggg         56         1   
11  17                    s                   s         56         1   
12  20        proyecto pepe    que tal soy sech         56         1   
13  21     allprojects test                sape         56         1   
14  24  getallprojects test                sest         56         1   

    maxMembers                 createdAt                 updatedAt  
0            5  2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z  
1            5  2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z  
2            5  2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z  
3            5  2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z  
4            5  2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z  
5            5  2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z  
6            5  2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z  
7            5  2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z  
8            5  2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z  
9            5  2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z  
10           5  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z  
11           5  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z  
12           5  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z  
13           5  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z  
14           5  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z

In [ ]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(10, 1)
(15, 1)
(45, 8)


In [ ]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)

print(df_final.shape)

(15, 8)


In [ ]:
df_final.head(10)

Palabra Palabra  id   name description  creatorId  statusId  maxMembers
0     dog     dog   1    cat        blue          2         1           5
1    aaaa     cat   2    dog         red          2         1           5
2  holaaa     dog   3  doggf         red         56         1           5
3    siii     cat   4  catff        blue         56         1           5
4    siii     cat   5  lemur        grey         56         1           5
5     dog   doggf   6    ppo         ppo         56         1           5
6     dog     cat   7    ddd         ddd         56         1           5
7     dog     cat   8  sssss         sss         56         1           5
8     cat     cat   9    sss         sss         56         1           5
9     wow     cat  10    ggg         ggg         56         1           5

ACA TENES QUE CONVERTIR TODOS LOS DATOS A VECTORES, CON EL CODIGO QUE TENES EN COLAB, PARA DESPUES PODER HACER FACTORIZACION DE MATRICES

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_features=5000)

In [ ]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [ ]:
print(type(vectorized_data))

<class 'scipy.sparse._csr.csr_matrix'>


In [ ]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [ ]:
vectorized_dataframe.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14
0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [ ]:
vectorized_dataframe.shape

(15, 15)

In [ ]:
from sklearn.decomposition import TruncatedSVD

In [ ]:
svd = TruncatedSVD(n_components=14)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [ ]:
reduced_data.shape

(15, 14)

In [ ]:
reduced_data

array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 8.98290721e-17,  0.00000000e+00,  1.00000000e+00,
        -1.11022302e-16, -1.66533454e-16, -1.12757026e-16,
        -2.22044605e-16, -3.12250226e-17,  6.93889390e-18,
        -3.33066907e-16, -1.66533454e-16,  1.78510458e-18,
         1.05083324e-18, -4.90269492e-18],
       [ 8.98290721e-17,  0.00000000e+00,  1.00000000e+00,
        -1.11022302e-16, -1.66533454e-16, -1.12757026e-16,
        -2.22044605e-16, -3.12250226e-17,  6.93889390e-18,
        -3.33066907e-16, -1.66533454e-16,  1.78510458e-18,
         1.05083324e-18, -4.90269492e-18],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.

In [ ]:
svd.explained_variance_ratio_.cumsum()

array([0.13684211, 0.27368421, 0.41052632, 0.48686778, 0.56482027,
       0.63101192, 0.70992045, 0.78620955, 0.84812493, 0.92388495,
       1.        , 1.        , 1.        , 1.        ])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(reduced_data)

In [ ]:
similarity

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  3.04330825e-17, -2.54758612e-17,
         1.37305033e-16,  1.29505995e-31,  1.29505995e-31,
        -5.39759778e-18,  1.56828484e-17,  0.00000000e+00,
         6.35716119e-18, -1.01422025e-16, -6.87780982e-17],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  3.04330825e-17, -2.54758612e-17,
         1.37305033e-16,  1.29505995e-31,  1.29505995e-31,
        -5.39759778e-18,  1.56828484e-17,  0.00000000e+00,
         6.35716119e-18, -1.01422025e-16, -6.87780982e-17],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000

In [ ]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  3.04330825e-17, -2.54758612e-17,
         1.37305033e-16,  1.29505995e-31,  1.29505995e-31,
        -5.39759778e-18,  1.56828484e-17,  0.00000000e+00,
         6.35716119e-18, -1.01422025e-16, -6.87780982e-17],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  3.04330825e-17, -2.54758612e-17,
         1.37305033e-16,  1.29505995e-31,  1.29505995e-31,
        -5.39759778e-18,  1.56828484e-17,  0.00000000e+00,
         6.35716119e-18, -1.01422025e-16, -6.87780982e-17],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000

In [ ]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

In [ ]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    movie_indices = [i[0] for i in sim_scores]

    recommended_projects = df_final['name'].iloc[movie_indices].tolist()
    result_dict = {}
    for i, movie in enumerate(recommended_projects):
        result_dict[i + 1] = movie

    return result_dict

In [ ]:
get_recommendations("dog")

{1: 'doggf',
 2: 'ddd',
 3: 'lemur',
 4: 'modified bruuhhh',
 5: 'proyecto pepe',
 6: 'sssss',
 7: 'sss',
 8: 'cat',
 9: 'catff',
 10: 's',
 11: 'ggg',
 12: 'ppo',
 13: 'getallprojects test',
 14: 'allprojects test'}