# Instalamos las librerias necesarias

In [41]:
%pip install pandas
%pip install requests
%pip install numpy
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


### Importamos todas las librerias necesarias para poder realizar el modelo

In [42]:
import pandas as pd
import requests

In [43]:
from fastapi import FastAPI

In [44]:
headers = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

### Conseguimos el ID del usuario que haya ingresado a la pagina web

In [45]:
payload = {
    "email": "gordinho",
    "password": "rey"
}
us = requests.post("http://localhost:3000/auth/login", json=payload)

print(us.json())
json_data = us.json()

user_id = json_data.get('id')

print(user_id)

{'Success': 'Login Success', 'id': 67, 'accessToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjcsImVtYWlsIjoiZ29yZGluaG8iLCJwYXNzd29yZCI6IiQyYiQxMCR0bE0yQXJNNnppakY2SXd0RldSRk51Z1VFMWJqdzJEakxITU53eURwQ1pIV3dwWFBlaEkxNiIsInVzZXJOYW1lIjoiZ3JvZGluaG9vbyIsImFib3V0IjoibWUgZ3VzdGEgY29tZXJlbWUgdW5vcyBlbXBhdHl6YW5kb3MiLCJpYXQiOjE3MDEyOTA4NzQsImV4cCI6MTcwMTM4MDg3NH0.1agbcOt2g-Owb6cLpYfFOv6M-aRByRdNFwCCSQeVBvc', 'refreshToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjcsImVtYWlsIjoiZ29yZGluaG8iLCJwYXNzd29yZCI6IiQyYiQxMCR0bE0yQXJNNnppakY2SXd0RldSRk51Z1VFMWJqdzJEakxITU53eURwQ1pIV3dwWFBlaEkxNiIsInVzZXJOYW1lIjoiZ3JvZGluaG9vbyIsImFib3V0IjoibWUgZ3VzdGEgY29tZXJlbWUgdW5vcyBlbXBhdHl6YW5kb3MiLCJpYXQiOjE3MDEyOTA4NzR9.AP3BoZ0pjGEXkIgYH4-aV_ts6cJ8bpQ7-1Sciw_FrSk'}
67


#### Conseguimos el historial del usuario, tanto de proyectos, como en general, de todo lo que haya buscado dentro de la pagina web

In [46]:
app = FastAPI()

@app.get(f"http://localhost:3000/userData/searchHistory/{id}")
def get_search_history(id: int):
    return requests.get(f"http://localhost:3000/userData/searchHistory/{id}", headers=headers).json()

In [47]:
search_history_data = get_search_history(user_id)
search_history_data

'wow lemur lemur '

In [48]:
@app.get(f"http://localhost:3000/userData/visitHistory/{id}")
def get_visit_history(id: int):
    return requests.get(f"http://localhost:3000/userData/visitHistory/{id}", headers=headers).json()

In [49]:
visit_history_data = get_visit_history(user_id)
visit_history_data

'lemur lemur lemur lemur lemur lemur seses'

In [50]:
get_all_projects_url = "http://localhost:3000/userData/getAllProjects"
headers_projects = {
    "x-api-key": "REYDEREDES"
}
response_all_projects = requests.get(get_all_projects_url, headers=headers_projects)
all_projects_data = response_all_projects.json()

print(all_projects_data)

[{'id': 1, 'name': 'cat', 'description': 'blue', 'creatorId': 2, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023-10-30T13:39:26.619Z', 'updatedAt': '2023-10-30T13:39:26.619Z', 'collaborators': []}, {'id': 2, 'name': 'dog', 'description': 'red', 'creatorId': 2, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023-10-30T13:39:46.698Z', 'updatedAt': '2023-10-30T13:39:46.698Z', 'collaborators': []}, {'id': 3, 'name': 'doggf', 'description': 'red', 'creatorId': 56, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023-11-01T21:16:53.796Z', 'updatedAt': '2023-11-03T01:05:23.711Z', 'collaborators': [{'id': 3, 'userId': 56, 'projectId': 3}]}, {'id': 4, 'name': 'catff', 'description': 'blue', 'creatorId': 56, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023-11-01T21:17:02.209Z', 'updatedAt': '2023-11-03T01:06:51.653Z', 'collaborators': [{'id': 4, 'userId': 56, 'projectId': 4}]}, {'id': 5, 'name': 'lemur', 'description': 'grey', 'creatorId': 56, 'statusId': 1, 'maxMembers': 5, 'createdAt': '2023

In [51]:
print(type(search_history_data))
print(type(visit_history_data))
print(type(all_projects_data))


lista1 = search_history_data.split()
lista2 = visit_history_data.split()

all_projects_data[1]

<class 'str'>
<class 'str'>
<class 'list'>


{'id': 2,
 'name': 'dog',
 'description': 'red',
 'creatorId': 2,
 'statusId': 1,
 'maxMembers': 5,
 'createdAt': '2023-10-30T13:39:46.698Z',
 'updatedAt': '2023-10-30T13:39:46.698Z',
 'collaborators': []}

## Realizamos los dataframes con los datos recibidos

In [52]:
df1 = pd.DataFrame({
    'Palabra': lista1
})

df2 = pd.DataFrame({
    'AllPalabra': lista2
})
df3 = pd.DataFrame(all_projects_data)

In [53]:
print(df1)
print("--------------------------------------------" + "\n")
print(df2)
print("--------------------------------------------" + "\n")
print(df3)

  Palabra
0     wow
1   lemur
2   lemur
--------------------------------------------

  AllPalabra
0      lemur
1      lemur
2      lemur
3      lemur
4      lemur
5      lemur
6      seses
--------------------------------------------

    id                                      name  \
0    1                                       cat   
1    2                                       dog   
2    3                                     doggf   
3    4                                     catff   
4    5                                     lemur   
5    6                                       ppo   
6    7                                       ddd   
7    8                                     sssss   
8    9                                       sss   
9   10                                       ggg   
10  15                          modified bruuhhh   
11  17                                         s   
12  20                             proyecto pepe   
13  21                          allp

In [54]:
df3.head(15)

id                 name         description  creatorId  statusId  \
0    1                  cat                blue          2         1   
1    2                  dog                 red          2         1   
2    3                doggf                 red         56         1   
3    4                catff                blue         56         1   
4    5                lemur                grey         56         1   
5    6                  ppo                 ppo         56         1   
6    7                  ddd                 ddd         56         1   
7    8                sssss                 sss         56         1   
8    9                  sss                 sss         56         1   
9   10                  ggg                 ggg         56         1   
10  15     modified bruuhhh  modified testinggg         56         1   
11  17                    s                   s         56         1   
12  20        proyecto pepe    que tal soy sech         56         1   
13  21     allprojects test                sape         56         1   
14  24  getallprojects test                sest         56         1   

    maxMembers                 createdAt                 updatedAt  \
0            5  2023-10-30T13:39:26.619Z  2023-10-30T13:39:26.619Z   
1            5  2023-10-30T13:39:46.698Z  2023-10-30T13:39:46.698Z   
2            5  2023-11-01T21:16:53.796Z  2023-11-03T01:05:23.711Z   
3            5  2023-11-01T21:17:02.209Z  2023-11-03T01:06:51.653Z   
4            5  2023-11-01T21:17:15.554Z  2023-11-01T21:17:15.554Z   
5            5  2023-11-01T22:23:22.617Z  2023-11-01T22:23:22.617Z   
6            5  2023-11-02T00:15:59.937Z  2023-11-02T00:15:59.937Z   
7            5  2023-11-02T00:16:07.463Z  2023-11-03T01:05:23.711Z   
8            5  2023-11-02T00:16:12.692Z  2023-11-02T00:16:12.692Z   
9            5  2023-11-02T00:16:20.825Z  2023-11-02T00:16:20.825Z   
10           5  2023-11-07T17:11:23.205Z  2023-11-08T12:01:22.303Z   
11           5  2023-11-07T17:30:10.962Z  2023-11-08T23:36:30.931Z   
12           5  2023-11-08T21:27:01.009Z  2023-11-08T21:27:01.009Z   
13           5  2023-11-08T23:06:27.831Z  2023-11-08T23:06:27.831Z   
14           5  2023-11-08T23:07:54.004Z  2023-11-08T23:07:54.004Z   

                                        collaborators  
0                                                  []  
1                                                  []  
2           [{'id': 3, 'userId': 56, 'projectId': 3}]  
3           [{'id': 4, 'userId': 56, 'projectId': 4}]  
4   [{'id': 5, 'userId': 56, 'projectId': 5}, {'id...  
5           [{'id': 6, 'userId': 56, 'projectId': 6}]  
6           [{'id': 8, 'userId': 56, 'projectId': 7}]  
7   [{'id': 9, 'userId': 56, 'projectId': 8}, {'id...  
8          [{'id': 10, 'userId': 56, 'projectId': 9}]  
9   [{'id': 11, 'userId': 56, 'projectId': 10}, {'...  
10        [{'id': 13, 'userId': 56, 'projectId': 15}]  
11        [{'id': 15, 'userId': 56, 'projectId': 17}]  
12        [{'id': 16, 'userId': 56, 'projectId': 20}]  
13        [{'id': 17, 'userId': 56, 'projectId': 21}]  
14  [{'id': 18, 'userId': 56, 'projectId': 24}, {'...

In [55]:
print(df1.shape)
print(df2.shape)
print(df3.shape)

(3, 1)
(7, 1)
(56, 9)


In [56]:
df_concatenated = pd.concat([df1, df2], axis=1)

df_final = pd.merge(df_concatenated, df3, left_index=True, right_index=True)

df_final = df_final.drop(['createdAt'], axis=1)
df_final = df_final.drop(['updatedAt'], axis=1)
df_final = df_final.drop(['statusId'], axis=1)
df_final = df_final.drop(['maxMembers'], axis=1)
df_final = df_final.drop(['collaborators'], axis=1)

print(df_final.shape)

(7, 6)


In [57]:
df_final.head(10)

Palabra AllPalabra  id   name description  creatorId
0     wow      lemur   1    cat        blue          2
1   lemur      lemur   2    dog         red          2
2   lemur      lemur   3  doggf         red         56
3     NaN      lemur   4  catff        blue         56
4     NaN      lemur   5  lemur        grey         56
5     NaN      lemur   6    ppo         ppo         56
6     NaN      seses   7    ddd         ddd         56

### Convierto todos los datos, a vectores a traves de TF-IDF

In [58]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [60]:
tfidf = TfidfVectorizer(max_features=5000)

In [61]:
vectorized_data = tfidf.fit_transform(df_final["description"])

In [62]:
print(type(vectorized_data))

<class 'scipy.sparse._csr.csr_matrix'>


In [63]:
vectorized_dataframe = pd.DataFrame(vectorized_data.toarray(), index=df_final["description"].index.tolist())

In [64]:
vectorized_dataframe.head()

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  1.0
2  0.0  0.0  0.0  0.0  1.0
3  1.0  0.0  0.0  0.0  0.0
4  0.0  0.0  1.0  0.0  0.0

In [65]:
vectorized_dataframe.shape

(7, 5)

In [66]:
from sklearn.decomposition import TruncatedSVD

In [67]:
com = vectorized_dataframe.shape[1] - 1

com

4

In [68]:
svd = TruncatedSVD(n_components=com)

reduced_data = svd.fit_transform(vectorized_dataframe)

In [69]:
reduced_data.shape

(7, 4)

In [70]:
reduced_data

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16,
        -5.55111512e-16],
       [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16,
        -5.55111512e-16],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00, -4.68375339e-17,  8.38116355e-01,
        -5.00449516e-01],
       [ 0.00000000e+00,  2.94902991e-17,  4.19058177e-01,
         3.35964891e-01],
       [ 0.00000000e+00,  1.22124533e-15,  3.49215148e-01,
         7.97920970e-01]])

In [71]:
svd.explained_variance_ratio_.cumsum()

array([0.26315789, 0.52631579, 0.64261874, 0.81627028])

# Realizamos la similitud de coseno con los datos ya vectorizados

In [72]:
from sklearn.metrics.pairwise import cosine_similarity

In [73]:
similarity = cosine_similarity(reduced_data)

In [74]:
similarity

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  4.59643190e-17, -4.65564687e-16,
         8.04562997e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  4.59643190e-17, -4.65564687e-16,
         8.04562997e-16],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  4.59643190e-17,  4.59643190e-17,
         0.00000000e+00,  1.00000000e+00,  3.49200343e-01,
        -1.25420626e-01],
       [ 0.00000000e+00, -4.65564687e-16, -4.65564687e-16,
         0.00000000e+00,  3.49200343e-01,  1.00000000e+00,
         8.85851910e-01],
       [ 0.00000000e+00,  8.04562997e-16,  8.04562997e-16,
         0.00000000e+00, -1.25420626e-01,  8.85851910e-01,
         1.0000000

In [75]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(reduced_data, reduced_data)

cosine_sim

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  4.48685390e-17, -2.50057287e-16,
         7.00768871e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  4.48685390e-17, -2.50057287e-16,
         7.00768871e-16],
       [ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  4.48685390e-17,  4.48685390e-17,
         0.00000000e+00,  9.52888743e-01,  1.83086045e-01,
        -1.06636236e-01],
       [ 0.00000000e+00, -2.50057287e-16, -2.50057287e-16,
         0.00000000e+00,  1.83086045e-01,  2.88482164e-01,
         4.14414895e-01],
       [ 0.00000000e+00,  7.00768871e-16,  7.00768871e-16,
         0.00000000e+00, -1.06636236e-01,  4.14414895e-01,
         7.5862909

In [76]:
indices = pd.Series(df_final.index, index=df_final['name']).drop_duplicates()

##### Funcion para obtener recomendaciones en base a un proyecto por default

In [77]:
def get_recommendations(name, cosine_sim=cosine_sim):
    idx = indices[name]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:20]

    project_indices = [i[0] for i in sim_scores]

    recommended_projects = [{"projectId": int(df_final['id'].iloc[i])} for i in project_indices]
    
    return recommended_projects

In [78]:
get_recommendations("dog")

[{'projectId': 3},
 {'projectId': 7},
 {'projectId': 5},
 {'projectId': 1},
 {'projectId': 4},
 {'projectId': 6}]

In [79]:
print(type(get_recommendations("dog")[0]))

<class 'dict'>


##### Enviando las recomendaciones

In [80]:
import json

url = "http://localhost:3000/recommendations/recommend"

datos_json = {
    "id": 55,
    "projectsWithAffinities": get_recommendations("dog")
}

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

print(datos_json)

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

respuesta = requests.post(url, data=json.dumps(datos_json), headers=encabezado)

if respuesta.status_code == 200:
    print('Solicitud exitosa. Respuesta del servidor:')
    print(respuesta.json())
else:
    print(f'Error en la solicitud. Código de estado: {respuesta.status_code}')
    print(respuesta.text)

{'id': 55, 'projectsWithAffinities': [{'projectId': 3}, {'projectId': 7}, {'projectId': 5}, {'projectId': 1}, {'projectId': 4}, {'projectId': 6}]}
Solicitud exitosa. Respuesta del servidor:
{'message': 'created recommendations'}


In [81]:
df_history = df_final.drop(["id"], axis=1)
df_history = df_history.drop(["name"], axis=1)
df_history = df_history.drop(["creatorId"], axis=1)
df_history = df_history.drop(["AllPalabra"], axis=1)

print(df_history.head(5))

  Palabra description
0     wow        blue
1   lemur         red
2   lemur         red
3     NaN        blue
4     NaN        grey


##### Funcion para hacer recomendaciones en base al historial del usuario

In [82]:
def recommend_projects():
    
    df_history['Palabra'] = df_history['Palabra'].astype(str)
    df_history['description'] = df_history['description'].astype(str)

    tfidf_vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = tfidf_vectorizer.fit_transform(df_history['description'], df_history['Palabra'])

    cosine_similarities = linear_kernel(tfidf_matrix, tfidf_matrix)

    search_similarity = cosine_similarities[-1]
    related_projects_indices = search_similarity.argsort()[:-1][::-1]
    recommended_projects = [{'projectId': project_id} for project_id in df_final.iloc[related_projects_indices]['id'].tolist()]
    
    return recommended_projects

In [83]:
recommendations = recommend_projects()
print("Proyectos recomendados:")
print(recommendations)

Proyectos recomendados:
[{'projectId': 6}, {'projectId': 5}, {'projectId': 4}, {'projectId': 3}, {'projectId': 2}, {'projectId': 1}]


##### Enviando resultados

In [85]:
import json

url = "http://localhost:3000/recommendations/recommend"

datos_json_history = {
    "id": user_id,
    "projectsWithAffinities": recommend_projects()
}

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

print(datos_json_history)

encabezado = {
    "Authorization": "Bearer",
    "Content-Type": "application/json",
    "x-api-key": "REYDEREDES"
}

respuesta = requests.post(url, data=json.dumps(datos_json_history), headers=encabezado)

if respuesta.status_code == 200:
    print('Solicitud exitosa. Respuesta del servidor:')
    print(respuesta.json())
else:
    print(f'Error en la solicitud. Código de estado: {respuesta.status_code}')
    print(respuesta.text)

{'id': 67, 'projectsWithAffinities': [{'projectId': 6}, {'projectId': 5}, {'projectId': 4}, {'projectId': 3}, {'projectId': 2}, {'projectId': 1}]}
Solicitud exitosa. Respuesta del servidor:
{'message': 'created recommendations'}
